import json, copy, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "messages")

with open(os.path.join(ROOT, "en.json"), "r", encoding="utf-8") as f:
    EN = json.load(f)

def deep_merge(base, over):
    r = copy.deepcopy(base)
    for k, v in over.items():
        if k in r and isinstance(r[k], dict) and isinstance(v, dict):
            r[k] = deep_merge(r[k], v)
        else:
            r[k] = v
    return r

def save(code, data):
    merged = deep_merge(EN, data)
    path = os.path.join(ROOT, f"{code}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"  wrote {code}.json")


# ── Dutch ─────────────────────────────────────────────────────────────────
save("nl", {
  "nav": {"catalog":"Catalogus","popup":"Popup","about":"Over ons","how":"Hoe het werkt","contacts":"Contact","startProject":"Project starten","openMenu":"Menu openen","closeMenu":"Menu sluiten","goToAccount":"Naar account","signIn":"Inloggen","cartItems":"Winkelwagen — {count} artikelen","mainNav":"Hoofdnavigatie","logoLink":"U:DO CRAFT — terug naar home"},
  "socialProof": {"trustedBy":"Vertrouwd door teams wereldwijd"},
  "about": {"label":"Over ons","heading":"Platform voor","headingHighlight":"bedrijfsmerchandise","desc1":"Van startups tot grote bedrijven — wij helpen teams merch te maken waar ze trots op zijn.","desc2":"Vanaf 10 stuks, geen verborgen kosten, eigen productie, persoonlijke accountmanager, kwaliteitsgarantie.","features":{"editor":{"title":"Online editor","desc":"Upload je logo, plaats het op het product en zie het resultaat direct."},"minOrder":{"title":"Vanaf 10 stuks","desc":"Ideaal voor startups en kleine teams."},"pricing":{"title":"Transparante prijzen","desc":"Direct factuur. Geen verborgen kosten."},"timeline":{"title":"7–14 dagen","desc":"Van bevestiging tot levering."},"quality":{"title":"Kwaliteitscontrole","desc":"Elke batch wordt gecontroleerd voor verzending."},"manager":{"title":"Persoonlijke accountmanager","desc":"Beschikbaar van eerste aanvraag tot levering."}}},
  "faq": {"heading":"Veelgestelde vragen","noAnswer":"Geen antwoord gevonden?","contactUs":"Neem contact op","replyTime":"— we reageren binnen een uur.","items":{"0":{"question":"Wat is de minimale bestelhoeveelheid?","answer":"Vanaf 10 stuks. Geen toeslag voor kleine aantallen."},"1":{"question":"Hoeveel kost het bedrukken?","answer":"De prijs hangt af van type (zeefdruk, borduurwerk, DTF) en hoeveelheid. Zie de online editor."},"2":{"question":"Hoe lang duurt een bestelling?","answer":"Standaard levertijd — 7–14 werkdagen na bevestiging."},"3":{"question":"Kan ik de kwaliteit zien voor een grote bestelling?","answer":"Ja. Box of Touch — fysieke staalkaarten van stoffen, kleuren en producten."},"4":{"question":"Wat als ik niet tevreden ben?","answer":"We keuren het ontwerp goed voor productie. Klopt het product niet — we maken het gratis opnieuw."},"5":{"question":"Zijn er kortingen voor grote bestellingen?","answer":"Ja. 10–49 stuks — basisprijs. 50–99 — 12% korting. 100+ — 15% korting."}}},
  "finalCta": {"ready":"Klaar om te beginnen?","heading":"Jouw merch — in 14 dagen","desc":"Van idee tot eindproduct. Online editor, persoonlijke accountmanager, kwaliteitsgarantie.","cta":"Project starten","footer":"Vanaf 10 stuks · Geen verborgen kosten · Levering inbegrepen"},
  "footer": {"readyToStart":"Klaar om te beginnen?","readyDesc":"Vanaf 10 stuks · 7–14 dagen · Levering","startProject":"Project starten","ariaLabel":"Voettekst","homeLink":"U:DO CRAFT — terug naar home","columns":{"products":{"title":"Producten","links":{"constructor":"Merch-configurator","catalog":"Catalogus","popup":"Popup-stand","box":"Box of Touch","designer":"Designer inhuren"}},"company":{"title":"Bedrijf","links":{"about":"Over ons","how":"Hoe het werkt","career":"Carrière","blog":"Blog"}},"support":{"title":"Ondersteuning","links":{"faq":"FAQ","contact":"Contact","cabinet":"Account","delivery":"Verzending en betaling"}}},"privacy":"Privacy","terms":"Voorwaarden","cookies":"Cookies"},
  "cart": {"title":"Winkelwagen","titleWithCount":"Winkelwagen ({count})","empty":"De winkelwagen is leeg","emptyDesc":"Kies een product en configureer de bedrukking","toCatalog":"Naar catalogus","ariaLabel":"Winkelwagen","quantity":"{qty} st · {size}","total":"Totaal:","cartItem":"Winkelwagenartikel"},
  "contactForm": {"nameLabel":"Uw naam *","namePlaceholder":"Jan Jansen","emailLabel":"E-mail *","emailPlaceholder":"hr@bedrijf.nl","phoneLabel":"Telefoon *","phonePlaceholder":"+31 XX XXXXXXX","companyLabel":"Bedrijf","companyPlaceholder":"Bedrijfsnaam","topicLabel":"Onderwerp *","messageLabel":"Vertel ons over uw project","messagePlaceholder":"Hoeveelheid, producttype, deadlines...","filesLabel":"Bestanden uploaden (ontwerpen, logo's enz.)","filesClick":"Klik of sleep bestanden hierheen","filesDesc":"Ontwerpen, logo's, afbeeldingen...","submit":"Verzenden","submitting":"Verzenden...","error":"Er is een fout opgetreden. Probeer opnieuw of neem contact op.","success":"Bedankt voor uw bericht!","successDesc":"We hebben uw aanvraag ontvangen en nemen binnenkort contact op.","deleteFile":"Bestand verwijderen {name}","topics":{"merch":{"label":"Bedrijfsmerchandise","desc":"T-shirts, hoodies, accessoires voor uw team of merk"},"popup":{"label":"Popup-stand voor evenement","desc":"Live merch-personalisatie op uw evenement"},"box":{"label":"Box of Touch","desc":"Fysieke stalen van stoffen en producten voor productie"},"designer":{"label":"Ontwerpdiensten","desc":"Logo-ontwikkeling of aanpassing voor bedrukking"},"bulk":{"label":"Grote bestelling (500+)","desc":"Groothandelsbestellingen met individuele voorwaarden"},"other":{"label":"Overige","desc":"Elke andere vraag of suggestie"}}},
  "privacy": {"title":"Privacybeleid","noContent":"Inhoud nog niet toegevoegd."},
  "terms": {"title":"Algemene voorwaarden","noContent":"Inhoud nog niet toegevoegd."},
  "order": {"loadError":"Catalogus kon niet worden geladen. Vernieuw de pagina."},
  "leadMagnet": {"badge":"Gratis","heading":"Ontvang een gratis mockup van je merch","desc":"Upload je logo — we zetten het op een echt product en sturen de mockup naar je e-mail.","emailLabel":"Jouw e-mail","cta":"Mockup ontvangen","loading":"Verzenden...","emailError":"Voer een geldig e-mailadres in","success":"Bedankt!","successDesc":"De mockup komt binnen 24 uur in je inbox aan","formLabel":"Mockup-aanvraagformulier","orCalculate":"Wil je de prijs nu weten?","openCalculator":"Prijscalculator openen →"},
  "popup": {"badge":"Mobiele popup-service","heroHeading":"Merch-popup op jouw evenement —","heroSubheading":"een live ervaring die men niet vergeet","heroDesc":"Wij komen naar u toe. Gasten kiezen kleding, personaliseren de bedrukking ter plaatse en vertrekken met hun merch.","bookBtn":"Popup boeken","howItWorks":"Hoe het werkt","nav":{"useCases":"Voor wie","how":"Hoe het werkt","faq":"FAQ","contacts":"Contact"},"book":"Boeken","footerCopyright":"U:DO CRAFT. Alle rechten voorbehouden.","menuOpen":"Menu openen","menuClose":"Menu sluiten","homeLink":"Home","stats":{"events":"Uitgevoerde popups","time":"Personalisatietijd","guests":"Gasten per evenement","satisfaction":"Tevreden organisatoren"},"useCases":{"label":"Voor wie","heading":"Geschikt voor elk evenement","items":{"corporate":{"title":"Bedrijfsevenementen","desc":"Maak het evenement onvergetelijk — gasten gaan naar huis met gepersonaliseerd merch."},"conferences":{"title":"Conferenties en forums","desc":"Gebrandmerkt merch ter plaatse — beste netwerktool."},"festivals":{"title":"Festivals en markten","desc":"Popup-stand die aandacht trekt. Live personalisatie — het is een show."},"launches":{"title":"Productlanceringen","desc":"Lancering met merch die gasten zelf maakten."},"universities":{"title":"Universiteiten en scholen","desc":"Diploma-uitreikingen, open dagen, studentenevenementen."},"b2b":{"title":"B2B-evenementen","desc":"Partnervergaderingen, beurzen, presentaties."}}},"process":{"label":"Proces","heading":"Drie stappen naar de perfecte popup","steps":{"0":{"step":"01","title":"Formaat kiezen","desc":"Vertel ons over het evenement — aantal gasten, locatie, datum."},"1":{"step":"02","title":"Stand voorbereiden","desc":"We brengen apparatuur, kleding en alles voor personalisatie."},"2":{"step":"03","title":"Gasten personaliseren","desc":"Elke gast kiest een product, plaatst de bedrukking en vertrekt met zijn merch."}}},"faq":{"label":"FAQ","heading":"Veelgestelde vragen","items":{"0":{"q":"Minimum aantal deelnemers?","a":"Vanaf 50 personen."},"1":{"q":"Hoe lang duurt personalisatie van één product?","a":"3 tot 10 minuten afhankelijk van de complexiteit."},"2":{"q":"Welke producten zijn beschikbaar?","a":"T-shirts, hoodies, longsleeves, petten en accessoires."},"3":{"q":"Wie betaalt het merch?","a":"Beide opties zijn mogelijk."},"4":{"q":"Hoe ver van tevoren boeken?","a":"We raden 2–3 weken voor het evenement aan."}}},"contact":{"label":"Boeken","heading":"Vertel ons over uw evenement","desc":"Laat een aanvraag achter — een accountmanager neemt binnen één werkdag contact op.","benefits":{"0":"Gratis adviesgesprek","1":"Individuele kostenschatting","2":"Reactie binnen 24 uur"}}}
})

# ── Portuguese ────────────────────────────────────────────────────────────
save("pt", {
  "nav": {"catalog":"Catálogo","popup":"Popup","about":"Sobre nós","how":"Como funciona","contacts":"Contato","startProject":"Iniciar projeto","openMenu":"Abrir menu","closeMenu":"Fechar menu","goToAccount":"Ir para a conta","signIn":"Entrar","cartItems":"Carrinho — {count} itens","mainNav":"Navegação principal","logoLink":"U:DO CRAFT — voltar ao início"},
  "socialProof": {"trustedBy":"Confiança de equipes ao redor do mundo"},
  "about": {"label":"Sobre nós","heading":"Plataforma de","headingHighlight":"merchandising corporativo","desc1":"De startups a grandes corporações — ajudamos equipes a criar merch do qual se orgulham.","desc2":"A partir de 10 unidades, sem taxas ocultas, produção própria, gerente pessoal, garantia de qualidade.","features":{"editor":{"title":"Editor online","desc":"Faça upload do logo, posicione no produto e veja o resultado imediatamente."},"minOrder":{"title":"A partir de 10 unidades","desc":"Perfeito para startups e equipes pequenas."},"pricing":{"title":"Preço transparente","desc":"Fatura imediata. Sem taxas ocultas."},"timeline":{"title":"7–14 dias","desc":"Da confirmação à entrega."},"quality":{"title":"Controle de qualidade","desc":"Cada lote é inspecionado antes do envio."},"manager":{"title":"Gerente pessoal","desc":"Disponível do primeiro pedido à entrega."}}},
  "faq": {"heading":"Perguntas frequentes","noAnswer":"Não encontrou resposta?","contactUs":"Fale conosco","replyTime":"— respondemos em uma hora.","items":{"0":{"question":"Qual é o pedido mínimo?","answer":"A partir de 10 unidades. Sem acréscimo para tiragens pequenas."},"1":{"question":"Quanto custa a impressão?","answer":"O preço depende do tipo (serigrafia, bordado, DTF) e da quantidade. Veja no editor online."},"2":{"question":"Quanto tempo leva um pedido?","answer":"Prazo padrão — 7–14 dias úteis após confirmação."},"3":{"question":"Posso ver a qualidade antes de um grande pedido?","answer":"Sim. Box of Touch — amostras físicas de tecidos, cores e produtos."},"4":{"question":"E se eu não gostar do resultado?","answer":"Aprovamos o design antes da produção. Se não corresponder — refazemos gratuitamente."},"5":{"question":"Há descontos para grandes pedidos?","answer":"Sim. 10–49 unidades — preço base. 50–99 — 12% desc. 100+ — 15% desc."}}},
  "finalCta": {"ready":"Pronto para começar?","heading":"Seu merch — em 14 dias","desc":"Da ideia ao produto final. Editor online, gerente pessoal, garantia de qualidade.","cta":"Iniciar projeto","footer":"A partir de 10 unidades · Sem taxas ocultas · Entrega incluída"},
  "footer": {"readyToStart":"Pronto para começar?","readyDesc":"A partir de 10 unidades · 7–14 dias · Entrega","startProject":"Iniciar projeto","ariaLabel":"Rodapé","homeLink":"U:DO CRAFT — voltar ao início","columns":{"products":{"title":"Produtos","links":{"constructor":"Configurador de merch","catalog":"Catálogo","popup":"Stand popup","box":"Box of Touch","designer":"Contratar designer"}},"company":{"title":"Empresa","links":{"about":"Sobre nós","how":"Como funciona","career":"Carreiras","blog":"Blog"}},"support":{"title":"Suporte","links":{"faq":"FAQ","contact":"Contato","cabinet":"Conta","delivery":"Envio e pagamento"}}},"privacy":"Privacidade","terms":"Termos","cookies":"Cookies"},
  "cart": {"title":"Carrinho","titleWithCount":"Carrinho ({count})","empty":"O carrinho está vazio","emptyDesc":"Escolha um produto e configure a impressão","toCatalog":"Ao catálogo","ariaLabel":"Carrinho","quantity":"{qty} uds · {size}","total":"Total:","cartItem":"Item do carrinho"},
  "contactForm": {"nameLabel":"Seu nome *","namePlaceholder":"João Silva","emailLabel":"E-mail *","emailPlaceholder":"hr@empresa.com","phoneLabel":"Telefone *","phonePlaceholder":"+55 XX XXXXX-XXXX","companyLabel":"Empresa","companyPlaceholder":"Nome da empresa","topicLabel":"Assunto *","messageLabel":"Conte-nos sobre seu projeto","messagePlaceholder":"Quantidade, tipo de produto, prazos...","filesLabel":"Enviar arquivos (designs, logos, etc.)","filesClick":"Clique ou arraste arquivos aqui","filesDesc":"Designs, logos, imagens...","submit":"Enviar","submitting":"Enviando...","error":"Ocorreu um erro. Tente novamente ou fale conosco diretamente.","success":"Obrigado por entrar em contato!","successDesc":"Recebemos sua solicitação e entraremos em contato em breve.","deleteFile":"Excluir arquivo {name}","topics":{"merch":{"label":"Merch corporativo","desc":"Camisetas, moletons, acessórios para sua equipe ou marca"},"popup":{"label":"Stand popup para evento","desc":"Personalização de merch ao vivo no seu evento"},"box":{"label":"Box of Touch","desc":"Amostras físicas de tecidos e produtos antes da produção"},"designer":{"label":"Serviços de design","desc":"Desenvolvimento ou adaptação de logotipos para impressão"},"bulk":{"label":"Pedido grande (500+)","desc":"Pedidos no atacado com condições individuais"},"other":{"label":"Outro","desc":"Qualquer outra dúvida ou sugestão"}}},
  "privacy": {"title":"Política de privacidade","noContent":"Conteúdo ainda não adicionado."},
  "terms": {"title":"Termos e condições","noContent":"Conteúdo ainda não adicionado."},
  "order": {"loadError":"Não foi possível carregar o catálogo. Por favor, atualize a página."},
  "leadMagnet": {"badge":"Grátis","heading":"Obtenha um mockup gratuito do seu merch","desc":"Faça upload do seu logo — nós aplicamos em um produto real e enviamos o mockup para o seu e-mail.","emailLabel":"Seu e-mail","cta":"Obter mockup","loading":"Enviando...","emailError":"Insira um e-mail válido","success":"Obrigado!","successDesc":"O mockup chegará na sua caixa de entrada em 24 horas","formLabel":"Formulário de mockup","orCalculate":"Quer saber o preço agora?","openCalculator":"Abrir calculadora de preços →"},
  "popup": {"badge":"Serviço popup móvel","heroHeading":"Popup de merch no seu evento —","heroSubheading":"uma experiência ao vivo que se lembra","heroDesc":"Vamos até você. Os convidados escolhem as roupas, personalizam a impressão no local e vão embora com seu merch.","bookBtn":"Reservar popup","howItWorks":"Como funciona","nav":{"useCases":"Para quem","how":"Como funciona","faq":"FAQ","contacts":"Contato"},"book":"Reservar","footerCopyright":"U:DO CRAFT. Todos os direitos reservados.","menuOpen":"Abrir menu","menuClose":"Fechar menu","homeLink":"Início","stats":{"events":"Popups realizados","time":"Tempo de personalização","guests":"Convidados por evento","satisfaction":"Organizadores satisfeitos"},"useCases":{"label":"Para quem","heading":"Adequado para qualquer evento","items":{"corporate":{"title":"Eventos corporativos","desc":"Torne o evento inesquecível — os convidados vão para casa com merch personalizado."},"conferences":{"title":"Conferências e fóruns","desc":"Merch com marca no local — melhor ferramenta de networking."},"festivals":{"title":"Festivais e feiras","desc":"Stand popup que chama atenção. Personalização ao vivo — é um show."},"launches":{"title":"Lançamentos de produto","desc":"Lançamento com merch que os convidados fizeram eles mesmos."},"universities":{"title":"Universidades e escolas","desc":"Formaturas, dias abertos, eventos estudantis."},"b2b":{"title":"Eventos B2B","desc":"Reuniões com parceiros, feiras, apresentações."}}},"process":{"label":"Processo","heading":"Três passos para o popup perfeito","steps":{"0":{"step":"01","title":"Escolher o formato","desc":"Conte-nos sobre o evento — número de convidados, local, data."},"1":{"step":"02","title":"Preparar o stand","desc":"Levamos equipamento, roupas e tudo necessário para a personalização."},"2":{"step":"03","title":"Convidados personalizam","desc":"Cada convidado escolhe um produto, coloca a impressão e vai embora com seu merch."}}},"faq":{"label":"FAQ","heading":"Perguntas frequentes","items":{"0":{"q":"Número mínimo de participantes?","a":"A partir de 50 pessoas."},"1":{"q":"Quanto tempo leva a personalização de um produto?","a":"De 3 a 10 minutos dependendo da complexidade."},"2":{"q":"Quais produtos estão disponíveis?","a":"Camisetas, moletons, mangas compridas, bonés e acessórios."},"3":{"q":"Quem paga o merch?","a":"Ambas as opções são possíveis."},"4":{"q":"Com quanto tempo de antecedência reservar?","a":"Recomendamos 2–3 semanas antes do evento."}}},"contact":{"label":"Reservar","heading":"Conte-nos sobre o seu evento","desc":"Deixe uma solicitação — um gerente entrará em contato em um dia útil.","benefits":{"0":"Consulta gratuita","1":"Orçamento individualizado","2":"Resposta em 24 horas"}}}
})

# ── Czech ─────────────────────────────────────────────────────────────────
save("cs", {
  "nav": {"catalog":"Katalog","popup":"Popup","about":"O nás","how":"Jak to funguje","contacts":"Kontakt","startProject":"Zahájit projekt","openMenu":"Otevřít menu","closeMenu":"Zavřít menu","goToAccount":"Přejít na účet","signIn":"Přihlásit se","cartItems":"Košík — {count} položek","mainNav":"Hlavní navigace","logoLink":"U:DO CRAFT — zpět na úvod"},
  "socialProof": {"trustedBy":"Důvěra týmů po celém světě"},
  "about": {"label":"O nás","heading":"Platforma pro","headingHighlight":"firemní merchandise","desc1":"Od startupů po velké korporace — pomáháme týmům vytvářet merch, na který jsou hrdé.","desc2":"Od 10 kusů, bez skrytých poplatků, vlastní výroba, osobní account manažer, záruka kvality.","features":{"editor":{"title":"Online editor","desc":"Nahrajte logo, umístěte ho na produkt a okamžitě uvidíte výsledek."},"minOrder":{"title":"Od 10 kusů","desc":"Ideální pro startupy a malé týmy."},"pricing":{"title":"Transparentní ceny","desc":"Faktura hned. Žádné skryté poplatky."},"timeline":{"title":"7–14 dní","desc":"Od potvrzení do doručení."},"quality":{"title":"Kontrola kvality","desc":"Každá dávka je zkontrolována před odesláním."},"manager":{"title":"Osobní account manažer","desc":"K dispozici od první poptávky až po doručení."}}},
  "faq": {"heading":"Časté dotazy","noAnswer":"Nenašli jste odpověď?","contactUs":"Napište nám","replyTime":"— odpovíme do hodiny.","items":{"0":{"question":"Jaká je minimální objednávka?","answer":"Od 10 kusů. Žádný příplatek za malé série."},"1":{"question":"Kolik stojí potisk?","answer":"Cena závisí na druhu (sítotisk, výšivka, DTF) a množství. Viz online editor."},"2":{"question":"Jak dlouho trvá objednávka?","answer":"Standardní lhůta — 7–14 pracovních dnů od potvrzení."},"3":{"question":"Mohu vidět kvalitu před velkou objednávkou?","answer":"Ano. Box of Touch — fyzické vzorky látek, barev a produktů."},"4":{"question":"Co když se mi výsledek nelíbí?","answer":"Design schvalujeme před výrobou. Pokud produkt neodpovídá — přepracujeme zdarma."},"5":{"question":"Jsou slevy na velké objednávky?","answer":"Ano. 10–49 ks — základní cena. 50–99 — 12% sleva. 100+ — 15% sleva."}}},
  "finalCta": {"ready":"Připraveni začít?","heading":"Váš merch — za 14 dní","desc":"Od nápadu k hotovému výrobku. Online editor, osobní account manažer, záruka kvality.","cta":"Zahájit projekt","footer":"Od 10 kusů · Bez skrytých poplatků · Doprava v ceně"},
  "footer": {"readyToStart":"Připraveni začít?","readyDesc":"Od 10 kusů · 7–14 dní · Doprava","startProject":"Zahájit projekt","ariaLabel":"Zápatí","homeLink":"U:DO CRAFT — zpět na úvod","columns":{"products":{"title":"Produkty","links":{"constructor":"Konfigurátor merche","catalog":"Katalog","popup":"Popup stánek","box":"Box of Touch","designer":"Najmout designéra"}},"company":{"title":"Společnost","links":{"about":"O nás","how":"Jak to funguje","career":"Kariéra","blog":"Blog"}},"support":{"title":"Podpora","links":{"faq":"FAQ","contact":"Kontakt","cabinet":"Účet","delivery":"Doprava a platba"}}},"privacy":"Soukromí","terms":"Podmínky","cookies":"Cookies"},
  "cart": {"title":"Košík","titleWithCount":"Košík ({count})","empty":"Košík je prázdný","emptyDesc":"Vyberte produkt a nakonfigurujte potisk","toCatalog":"Do katalogu","ariaLabel":"Košík","quantity":"{qty} ks · {size}","total":"Celkem:","cartItem":"Položka košíku"},
  "contactForm": {"nameLabel":"Vaše jméno *","namePlaceholder":"Jan Novák","emailLabel":"E-mail *","emailPlaceholder":"hr@firma.cz","phoneLabel":"Telefon *","phonePlaceholder":"+420 XXX XXX XXX","companyLabel":"Firma","companyPlaceholder":"Název firmy","topicLabel":"Předmět *","messageLabel":"Řekněte nám o svém projektu","messagePlaceholder":"Množství, typ produktu, termíny...","filesLabel":"Nahrát soubory (návrhy, loga atd.)","filesClick":"Klikněte nebo přetáhněte soubory sem","filesDesc":"Návrhy, loga, obrázky...","submit":"Odeslat","submitting":"Odesílám...","error":"Došlo k chybě. Zkuste to znovu nebo nás kontaktujte přímo.","success":"Děkujeme za kontakt!","successDesc":"Přijali jsme vaši žádost a brzy se ozveme.","deleteFile":"Smazat soubor {name}","topics":{"merch":{"label":"Firemní merch","desc":"Trička, mikiny, doplňky pro váš tým nebo značku"},"popup":{"label":"Popup stánek na akci","desc":"Live personalizace merche na vaší akci"},"box":{"label":"Box of Touch","desc":"Fyzické vzorky látek a produktů před výrobou"},"designer":{"label":"Designérské služby","desc":"Vývoj nebo adaptace loga pro potisk"},"bulk":{"label":"Velká objednávka (500+)","desc":"Velkoobchodní objednávky s individuálními podmínkami"},"other":{"label":"Jiné","desc":"Jakýkoliv jiný dotaz nebo návrh"}}},
  "privacy": {"title":"Zásady ochrany osobních údajů","noContent":"Obsah zatím nebyl přidán."},
  "terms": {"title":"Podmínky a pravidla","noContent":"Obsah zatím nebyl přidán."},
  "order": {"loadError":"Katalog se nepodařilo načíst. Obnovte stránku."},
  "leadMagnet": {"badge":"Zdarma","heading":"Získejte bezplatný mockup svého merche","desc":"Nahrajte logo — umístíme ho na skutečný výrobek a pošleme mockup na váš e-mail.","emailLabel":"Váš e-mail","cta":"Získat mockup","loading":"Odesílám...","emailError":"Zadejte platný e-mail","success":"Děkujeme!","successDesc":"Mockup dorazí do vaší schránky do 24 hodin","formLabel":"Formulář pro mockup","orCalculate":"Chcete znát cenu hned?","openCalculator":"Otevřít kalkulátor cen →"},
  "popup": {"badge":"Mobilní popup služba","heroHeading":"Merch popup na vaší akci —","heroSubheading":"živý zážitek, který se nezapomene","heroDesc":"Přijedeme k vám. Hosté si vyberou oblečení, přizpůsobí potisk na místě a odejdou s hotovým merchem.","bookBtn":"Rezervovat popup","howItWorks":"Jak to funguje","nav":{"useCases":"Pro koho","how":"Jak to funguje","faq":"FAQ","contacts":"Kontakt"},"book":"Rezervovat","footerCopyright":"U:DO CRAFT. Všechna práva vyhrazena.","menuOpen":"Otevřít menu","menuClose":"Zavřít menu","homeLink":"Úvod","stats":{"events":"Provedených popupů","time":"Čas personalizace","guests":"Hostů na jedné akci","satisfaction":"Spokojených organizátorů"},"useCases":{"label":"Pro koho","heading":"Vhodné pro jakoukoli akci","items":{"corporate":{"title":"Firemní akce","desc":"Udělejte akci nezapomenutelnou — hosté odejdou s osobním merchem."},"conferences":{"title":"Konference a fóra","desc":"Brandovaný merch na místě — nejlepší networkingový nástroj."},"festivals":{"title":"Festivaly a trhy","desc":"Popup stánek, který přitahuje pozornost. Live personalizace — to je show."},"launches":{"title":"Produktové launche","desc":"Launch s merchem, který hosté sami vyrobili."},"universities":{"title":"Univerzity a školy","desc":"Promoce, dny otevřených dveří, studentské akce."},"b2b":{"title":"B2B akce","desc":"Partnerská setkání, veletrhy, prezentace."}}},"process":{"label":"Proces","heading":"Tři kroky k dokonalému popupu","steps":{"0":{"step":"01","title":"Vybrat formát","desc":"Řekněte nám o akci — počet hostů, místo, datum."},"1":{"step":"02","title":"Připravíme stánek","desc":"Přivezeme vybavení, oblečení a vše potřebné k personalizaci."},"2":{"step":"03","title":"Hosté personalizují","desc":"Každý host si vybere výrobek, umístí potisk a odejde s merchem."}}},"faq":{"label":"FAQ","heading":"Časté dotazy","items":{"0":{"q":"Minimální počet účastníků?","a":"Od 50 osob."},"1":{"q":"Jak dlouho trvá personalizace jednoho výrobku?","a":"3 až 10 minut v závislosti na složitosti potisku."},"2":{"q":"Jaké produkty jsou dostupné?","a":"Trička, mikiny, longsleeve, čepice a doplňky."},"3":{"q":"Kdo platí za merch?","a":"Obě možnosti jsou v pořádku."},"4":{"q":"Jak předem rezervovat?","a":"Doporučujeme 2–3 týdny před akcí."}}},"contact":{"label":"Rezervovat","heading":"Řekněte nám o své akci","desc":"Zanechte žádost — account manažer se ozve do jednoho pracovního dne.","benefits":{"0":"Bezplatná konzultace","1":"Individuální kalkulace","2":"Odpověď do 24 hodin"}}}
})

# ── Swedish ───────────────────────────────────────────────────────────────
save("sv", {
  "nav": {"catalog":"Katalog","popup":"Popup","about":"Om oss","how":"Hur det fungerar","contacts":"Kontakt","startProject":"Starta projekt","openMenu":"Öppna meny","closeMenu":"Stäng meny","goToAccount":"Till kontot","signIn":"Logga in","cartItems":"Varukorg — {count} artiklar","mainNav":"Huvudnavigation","logoLink":"U:DO CRAFT — tillbaka till startsidan"},
  "socialProof": {"trustedBy":"Förtroende från team världen över"},
  "about": {"label":"Om oss","heading":"Plattform för","headingHighlight":"företagsmerchandise","desc1":"Från startups till stora företag — vi hjälper team att skapa merch de är stolta över.","desc2":"Från 10 stycken, inga dolda avgifter, egen produktion, personlig account manager, kvalitetsgaranti.","features":{"editor":{"title":"Online-redigerare","desc":"Ladda upp din logotyp, placera den på produkten och se resultatet direkt."},"minOrder":{"title":"Från 10 stycken","desc":"Perfekt för startups och små team."},"pricing":{"title":"Transparenta priser","desc":"Faktura direkt. Inga dolda avgifter."},"timeline":{"title":"7–14 dagar","desc":"Från bekräftelse till leverans."},"quality":{"title":"Kvalitetskontroll","desc":"Varje batch kontrolleras före leverans."},"manager":{"title":"Personlig account manager","desc":"Tillgänglig från första förfrågan till leverans."}}},
  "faq": {"heading":"Vanliga frågor","noAnswer":"Hittade du inget svar?","contactUs":"Kontakta oss","replyTime":"— vi svarar inom en timme.","items":{"0":{"question":"Vad är minsta beställningsmängden?","answer":"Från 10 stycken. Inget pristillägg för små beställningar."},"1":{"question":"Vad kostar trycket?","answer":"Priset beror på typ (screentryck, broderi, DTF) och mängd. Se online-redigeraren."},"2":{"question":"Hur lång tid tar en beställning?","answer":"Standardleveranstid — 7–14 arbetsdagar efter bekräftelse."},"3":{"question":"Kan jag se kvaliteten innan en stor beställning?","answer":"Ja. Box of Touch — fysiska prover på tyger, färger och produkter."},"4":{"question":"Vad händer om jag inte är nöjd med resultatet?","answer":"Vi godkänner designen före produktion. Om produkten inte stämmer — gör vi om gratis."},"5":{"question":"Finns det rabatter för stora beställningar?","answer":"Ja. 10–49 st — grundpris. 50–99 — 12% rabatt. 100+ — 15% rabatt."}}},
  "finalCta": {"ready":"Redo att börja?","heading":"Ditt merch — på 14 dagar","desc":"Från idé till färdig produkt. Online-redigerare, personlig account manager, kvalitetsgaranti.","cta":"Starta projekt","footer":"Från 10 stycken · Inga dolda avgifter · Leverans ingår"},
  "footer": {"readyToStart":"Redo att börja?","readyDesc":"Från 10 stycken · 7–14 dagar · Leverans","startProject":"Starta projekt","ariaLabel":"Sidfot","homeLink":"U:DO CRAFT — tillbaka till startsidan","columns":{"products":{"title":"Produkter","links":{"constructor":"Merch-konfigurator","catalog":"Katalog","popup":"Popup-ställ","box":"Box of Touch","designer":"Anlita designer"}},"company":{"title":"Företag","links":{"about":"Om oss","how":"Hur det fungerar","career":"Karriär","blog":"Blogg"}},"support":{"title":"Support","links":{"faq":"FAQ","contact":"Kontakt","cabinet":"Konto","delivery":"Frakt och betalning"}}},"privacy":"Integritet","terms":"Villkor","cookies":"Cookies"},
  "cart": {"title":"Varukorg","titleWithCount":"Varukorg ({count})","empty":"Varukorgen är tom","emptyDesc":"Välj en produkt och konfigurera trycket","toCatalog":"Till katalogen","ariaLabel":"Varukorg","quantity":"{qty} st · {size}","total":"Totalt:","cartItem":"Varukorgsobjekt"},
  "contactForm": {"nameLabel":"Ditt namn *","namePlaceholder":"Erik Svensson","emailLabel":"E-post *","emailPlaceholder":"hr@foretag.se","phoneLabel":"Telefon *","phonePlaceholder":"+46 XX XXX XXXX","companyLabel":"Företag","companyPlaceholder":"Företagsnamn","topicLabel":"Ämne *","messageLabel":"Berätta om ditt projekt","messagePlaceholder":"Antal, produkttyp, tidsfrister...","filesLabel":"Ladda upp filer (designer, logotyper etc.)","filesClick":"Klicka eller dra filer hit","filesDesc":"Designer, logotyper, bilder...","submit":"Skicka","submitting":"Skickar...","error":"Ett fel inträffade. Försök igen eller kontakta oss direkt.","success":"Tack för att du kontaktade oss!","successDesc":"Vi har tagit emot din förfrågan och hör av oss snart.","deleteFile":"Ta bort fil {name}","topics":{"merch":{"label":"Företagsmerch","desc":"T-shirts, hoodies, accessoarer för ditt team eller varumärke"},"popup":{"label":"Popup-ställ för evenemang","desc":"Live merch-personalisering på ditt evenemang"},"box":{"label":"Box of Touch","desc":"Fysiska prover på tyger och produkter innan produktion"},"designer":{"label":"Designertjänster","desc":"Logotyputveckling eller anpassning för tryck"},"bulk":{"label":"Stor beställning (500+)","desc":"Partihandelsbeställningar med individuella villkor"},"other":{"label":"Övrigt","desc":"Alla andra frågor eller förslag"}}},
  "privacy": {"title":"Integritetspolicy","noContent":"Innehåll har inte lagts till än."},
  "terms": {"title":"Villkor och bestämmelser","noContent":"Innehåll har inte lagts till än."},
  "order": {"loadError":"Det gick inte att läsa in katalogen. Uppdatera sidan."},
  "leadMagnet": {"badge":"Gratis","heading":"Få en gratis mockup av ditt merch","desc":"Ladda upp din logotyp — vi sätter den på en riktig produkt och skickar en mockup till din e-post.","emailLabel":"Din e-post","cta":"Hämta mockup","loading":"Skickar...","emailError":"Ange en giltig e-postadress","success":"Tack!","successDesc":"Mockupen kommer till din inkorg inom 24 timmar","formLabel":"Mockup-ansökningsformulär","orCalculate":"Vill du veta priset nu?","openCalculator":"Öppna priskalkylator →"},
  "popup": {"badge":"Mobil popup-service","heroHeading":"Merch-popup på ditt evenemang —","heroSubheading":"en liveupplevelse man inte glömmer","heroDesc":"Vi kommer till dig. Gäster väljer kläder, anpassar trycket på plats och lämnar med färdigt merch.","bookBtn":"Boka popup","howItWorks":"Hur det fungerar","nav":{"useCases":"För vem","how":"Hur det fungerar","faq":"FAQ","contacts":"Kontakt"},"book":"Boka","footerCopyright":"U:DO CRAFT. Alla rättigheter förbehållna.","menuOpen":"Öppna meny","menuClose":"Stäng meny","homeLink":"Startsida","stats":{"events":"Genomförda popups","time":"Personaliseringstid","guests":"Gäster per evenemang","satisfaction":"Nöjda arrangörer"},"useCases":{"label":"För vem","heading":"Lämplig för alla evenemang","items":{"corporate":{"title":"Företagsevenemang","desc":"Gör evenemanget oförglömligt — gäster åker hem med personligt merch."},"conferences":{"title":"Konferenser och forum","desc":"Varumärkesmerch på plats — bästa nätverkingsverktyget."},"festivals":{"title":"Festivaler och marknader","desc":"Popup-ställ som väcker uppmärksamhet. Live-personalisering — det är ett show."},"launches":{"title":"Produktlanseringar","desc":"Lansering med merch som gästerna skapade själva."},"universities":{"title":"Universitet och skolor","desc":"Examensceremoni, öppna hus, studentevenemang."},"b2b":{"title":"B2B-evenemang","desc":"Partnermöten, mässor, presentationer."}}},"process":{"label":"Process","heading":"Tre steg till den perfekta popupen","steps":{"0":{"step":"01","title":"Välj format","desc":"Berätta om evenemanget — antal gäster, plats, datum."},"1":{"step":"02","title":"Vi förbereder ståndet","desc":"Vi tar med utrustning, kläder och allt som behövs för personalisering."},"2":{"step":"03","title":"Gäster personaliserar","desc":"Varje gäst väljer en produkt, sätter trycket och lämnar med sitt merch."}}},"faq":{"label":"FAQ","heading":"Vanliga frågor","items":{"0":{"q":"Minsta antal deltagare?","a":"Från 50 personer."},"1":{"q":"Hur lång tid tar det att personalisera en produkt?","a":"3 till 10 minuter beroende på komplexitet."},"2":{"q":"Vilka produkter finns tillgängliga?","a":"T-shirts, hoodies, långärmade tröjor, kepsar och accessoarer."},"3":{"q":"Vem betalar för merchen?","a":"Båda alternativen är möjliga."},"4":{"q":"Hur långt i förväg boka?","a":"Vi rekommenderar 2–3 veckor före evenemanget."}}},"contact":{"label":"Boka","heading":"Berätta om ditt evenemang","desc":"Lämna en förfrågan — en account manager kontaktar dig inom en arbetsdag.","benefits":{"0":"Gratis konsultation","1":"Individuell kostnadsberäkning","2":"Svar inom 24 timmar"}}}
})

print("\nAll locale files generated successfully!")
print("Locales: en, de, fr, es, it, pl, nl, pt, cs, sv")
