import json, copy, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "messages")
with open(os.path.join(ROOT, "en.json"), "r", encoding="utf-8") as f:
    EN = json.load(f)

def deep_merge(base, over):
    r = copy.deepcopy(base)
    for k, v in over.items():
        if k in r and isinstance(r[k], dict) and isinstance(v, dict):
            r[k] = deep_merge(r[k], v)
        else:
            r[k] = v
    return r

def save(code, data):
    merged = deep_merge(EN, data)
    path = os.path.join(ROOT, f"{code}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"  wrote {code}.json")

COMMON_FAQ = lambda items: {"faq": {"items": {str(i): v for i, v in enumerate(items)}}}


# ── German ────────────────────────────────────────────────────────────────
save("de", {
  "nav":{"catalog":"Katalog","popup":"Popup","about":"Über uns","how":"So funktioniert's","contacts":"Kontakt","startProject":"Projekt starten","openMenu":"Menü öffnen","closeMenu":"Menü schließen","goToAccount":"Zum Konto","signIn":"Anmelden","cartItems":"Warenkorb — {count} Artikel","mainNav":"Hauptnavigation","logoLink":"U:DO CRAFT — zur Startseite"},
  "socialProof":{"trustedBy":"Das Vertrauen von Teams weltweit"},
  "about":{"label":"Über uns","heading":"Plattform für","headingHighlight":"Corporate Merchandise","desc1":"Von Startups bis zu Großunternehmen — wir helfen Teams, Merch zu erstellen, auf den sie stolz sind.","desc2":"Ab 10 Stück, keine versteckten Gebühren, eigene Produktion, persönlicher Ansprechpartner, Qualitätsgarantie.","features":{"editor":{"title":"Online-Editor","desc":"Logo hochladen, auf dem Produkt platzieren und sofort das Ergebnis sehen."},"minOrder":{"title":"Ab 10 Stück","desc":"Ideal für Startups und kleine Teams."},"pricing":{"title":"Transparente Preise","desc":"Sofortige Rechnung. Keine versteckten Gebühren."},"timeline":{"title":"7–14 Tage","desc":"Von der Bestätigung bis zur Lieferung."},"quality":{"title":"Qualitätskontrolle","desc":"Jede Charge wird vor dem Versand geprüft."},"manager":{"title":"Persönlicher Ansprechpartner","desc":"Von der ersten Anfrage bis zur Lieferung erreichbar."}}},
  "problemSolution":{"problemHeading":"Der Markt ist überschwemmt mit billigem Merch, den niemand trägt","problemsLabel":"Häufige Probleme","problems":{"minOrder":"Mindestbestellmenge 500+ Stück","approvals":"Wochenlange Design-Freigaben","quality":"Qualität entspricht nicht den Erwartungen","hidden":"Versteckte Kosten nach der Bestellung"},"solutionHeading":"Merch, der Teil Ihrer Marke wird","solutionsLabel":"U:DO Vorteile","solutions":{"minOrder":"Ab 10 Stück ohne Aufschlag","editor":"Online-Editor — Ergebnis sofort","samples":"Muster vor der Produktion (Box of Touch)","price":"Festpreis in der Rechnung"},"ctaLabel":"Katalog ansehen"},
  "collections":{"heading":"Katalog","allProducts":"Alle Produkte","all":"Alle","empty":"Keine Produkte in dieser Kategorie","prevPage":"Zurück","nextPage":"Weiter","page":"Seite {n}"},
  "boxOfTouch":{"label":"Box of Touch","heading":"Qualität erleben","headingHighlight":"bevor Sie bestellen","desc":"Die meisten Unternehmen bestellen blind. Box of Touch löst das: ein physisches Set aus Stoff-, Farb- und Produktmustern.","contentsLabel":"Inhalt der Box of Touch","contents":{"products":{"label":"Produktmuster","desc":"T-Shirts, Hoodies, Longsleeves — Schnitt und Passform fühlen"},"fabrics":{"label":"Stoffmuster","desc":"Verschiedene Zusammensetzungen und Gewichte"},"palette":{"label":"Farbpalette","desc":"Alle verfügbaren Farben mit echten Mustern"},"printing":{"label":"Druckarten","desc":"Siebdruck, Stickerei, DTF — zum Vergleich anfassen"}},"cta":"Box of Touch bestellen","freeDelivery":"Kostenloser Versand · Keine Verpflichtungen"},
  "faq":{"heading":"Häufig gestellte Fragen","noAnswer":"Keine Antwort gefunden?","contactUs":"Kontaktieren Sie uns","replyTime":"— wir antworten innerhalb einer Stunde.","items":{"0":{"question":"Was ist die Mindestbestellmenge?","answer":"Ab 10 Stück. Kein Aufschlag für kleine Auflagen."},"1":{"question":"Was kostet der Druck?","answer":"Der Preis hängt von der Druckart (Siebdruck, Stickerei, DTF) und der Menge ab."},"2":{"question":"Wie lange dauert eine Bestellung?","answer":"Standardlieferzeit — 7–14 Werktage nach Bestätigung."},"3":{"question":"Kann ich die Qualität prüfen?","answer":"Ja. Box of Touch enthält physische Muster von Stoffen, Farben und Produkten."},"4":{"question":"Was, wenn mir das Ergebnis nicht gefällt?","answer":"Wir genehmigen das Design vor der Produktion. Entspricht das Produkt nicht — machen wir es kostenlos neu."},"5":{"question":"Gibt es Rabatte bei Großbestellungen?","answer":"Ja. 10–49 Stück — Basispreis. 50–99 — 12% Rabatt. 100+ — 15% Rabatt."}}},
  "finalCta":{"ready":"Bereit anzufangen?","heading":"Ihr Merch — in 14 Tagen","desc":"Von der Idee zum fertigen Produkt. Online-Editor, persönlicher Ansprechpartner, Qualitätsgarantie.","cta":"Projekt starten","footer":"Ab 10 Stück · Keine versteckten Gebühren · Lieferung inklusive"},
  "footer":{"readyToStart":"Bereit anzufangen?","readyDesc":"Ab 10 Stück · 7–14 Tage · Lieferung","startProject":"Projekt starten","ariaLabel":"Fußzeile","homeLink":"U:DO CRAFT — zur Startseite","columns":{"products":{"title":"Produkte","links":{"constructor":"Merch-Konfigurator","catalog":"Katalog","popup":"Popup-Stand","box":"Box of Touch","designer":"Designer beauftragen"}},"company":{"title":"Unternehmen","links":{"about":"Über uns","how":"So funktioniert's","career":"Karriere","blog":"Blog"}},"support":{"title":"Support","links":{"faq":"FAQ","contact":"Kontakt","cabinet":"Konto","delivery":"Versand & Zahlung"}}},"privacy":"Datenschutz","terms":"AGB","cookies":"Cookies"},
  "cart":{"title":"Warenkorb","titleWithCount":"Warenkorb ({count})","empty":"Der Warenkorb ist leer","emptyDesc":"Produkt wählen und Druck konfigurieren","toCatalog":"Zum Katalog","ariaLabel":"Warenkorb","quantity":"{qty} Stk · {size}","total":"Gesamt:","cartItem":"Warenkorb-Artikel"},
  "checkout":{"title":"Warenkorb","orderTitle":"Bestellung aufgeben","stepCart":"Warenkorb","stepForm":"Unternehmensdaten","emptyCart":"Warenkorb ist leer","toCatalog":"Zum Katalog","total":"Gesamt","finalPriceNote":"Endpreis wird mit dem Ansprechpartner vereinbart","placeOrder":"Bestellung aufgeben","edit":"Bearbeiten","discount":"-{pct}% Rabatt","company":{"title":"Unternehmensdaten","name":"Firmenname *","namePlaceholder":"GmbH «Name»","taxId":"Steuernummer","taxIdPlaceholder":"DE123456789"},"contact":{"title":"Ansprechpartner","fullName":"Vor- und Nachname *","fullNamePlaceholder":"Hans Müller","email":"E-Mail *","emailPlaceholder":"hr@firma.de","phone":"Telefon","phonePlaceholder":"+49 XXX XXXXXXX","social":"Telegram / Instagram","socialPlaceholder":"@benutzername oder Link"},"delivery":{"title":"Lieferung & Fristen","options":{"nova_poshta":{"label":"DHL","desc":"2–3 Werktage"},"ukrposhta":{"label":"DPD","desc":"4–6 Werktage"},"pickup":{"label":"Abholung","desc":"Nach Vereinbarung"}},"deadline":"Gewünschter Termin","comment":"Anmerkung","commentPlaceholder":"Besondere Wünsche, Druckdetails..."},"submit":"Bestellung bestätigen","submitting":"Wird gesendet...","finalPriceManager":"Endpreis und Rechnung werden vom Ansprechpartner nach Bestätigung gesendet","success":{"title":"Bestellung eingegangen!","desc":"Unser Ansprechpartner meldet sich innerhalb von 24 Stunden.","createAccount":"Persönliches Konto erstellen","loginAccount":"Im Konto anmelden","createAccountDesc":"Bestellstatus verfolgen, chatten und Rechnungen einsehen.","emailExists":"Diese E-Mail ist bereits registriert.","emailLabel":"E-Mail","passwordLabel":"Passwort","newPasswordLabel":"Passwort erstellen","passwordPlaceholder":"Mindestens 6 Zeichen","enterPasswordPlaceholder":"Passwort eingeben","creating":"Wird erstellt...","create":"Konto erstellen","loggingIn":"Anmeldung...","login":"Anmelden","passwordError":"Passwort muss mindestens 6 Zeichen haben","enterPasswordError":"Passwort eingeben","wrongPassword":"Falsches Passwort","registrationError":"Registrierungsfehler. Später erneut versuchen.","skip":"Überspringen, zur Startseite","accountCreated":{"title":"Konto erstellt!","desc":"Wir haben eine Bestätigungs-E-Mail an {email} gesendet.","loginBtn":"Im Konto anmelden","homeLink":"Zur Startseite"}},"back":"Zurück","header":"U:DO","backAriaLabel":"Zurück"},
  "cabinet":{"breadcrumb":"/ Konto","settings":"Einstellungen","logout":"Abmelden","noOrders":"Noch keine Bestellungen","toCatalog":"Zum Katalog","writeTo":"Ansprechpartner schreiben","tabs":{"details":"Details","chat":"Chat","files":"Dateien"},"status":{"new":"Neue Anfrage","in_progress":"In Bearbeitung","production":"Produktion","completed":"Abgeschlossen","archived":"Archiv"},"delivery":{"nova_poshta":"DHL","ukrposhta":"DPD","pickup":"Abholung"},"details":{"phone":"Telefon","email":"E-Mail","company":"Unternehmen","orderDate":"Bestelldatum","orderAmount":"Bestellbetrag","delivery":"Lieferung","deadline":"Frist","positions":"Positionen ({n})","attachments":"Anhänge ({n})","invoice":"Rechnung herunterladen","print":"Druck"},"chat":{"placeholder":"Nachricht...","sendLabel":"Nachricht senden","attachLabel":"Datei anhängen","loading":"Nachrichten werden geladen...","empty":"Noch keine Nachrichten","fileTooLarge":"\"{name}\" überschreitet 10 MB"},"files":{"empty":"Noch keine Dateien","openFile":"Datei öffnen"}},
  "contactForm":{"nameLabel":"Ihr Name *","namePlaceholder":"Hans Müller","emailLabel":"E-Mail *","emailPlaceholder":"hr@firma.de","phoneLabel":"Telefon *","phonePlaceholder":"+49 XXX XXXXXXX","companyLabel":"Unternehmen","companyPlaceholder":"Firmenname","topicLabel":"Betreff *","messageLabel":"Erzählen Sie von Ihrem Projekt","messagePlaceholder":"Menge, Produkttyp, Fristen...","filesLabel":"Dateien hochladen","filesClick":"Klicken oder Dateien ziehen","filesDesc":"Designs, Logos, Bilder...","submit":"Senden","submitting":"Wird gesendet...","error":"Fehler. Bitte erneut versuchen.","success":"Vielen Dank!","successDesc":"Wir haben Ihre Anfrage erhalten.","deleteFile":"Datei löschen {name}","topics":{"merch":{"label":"Corporate Merch","desc":"T-Shirts, Hoodies, Accessoires"},"popup":{"label":"Popup-Stand","desc":"Live-Personalisierung auf Ihrer Veranstaltung"},"box":{"label":"Box of Touch","desc":"Physische Muster vor der Produktion"},"designer":{"label":"Designerleistungen","desc":"Logo-Entwicklung oder -Anpassung"},"bulk":{"label":"Großbestellung (500+)","desc":"Großhandel mit individuellen Konditionen"},"other":{"label":"Sonstiges","desc":"Jede andere Frage"}}},
  "privacy":{"title":"Datenschutzerklärung","noContent":"Inhalt noch nicht hinzugefügt."},
  "terms":{"title":"Allgemeine Geschäftsbedingungen","noContent":"Inhalt noch nicht hinzugefügt."},
  "order":{"loadError":"Katalog konnte nicht geladen werden. Seite neu laden."},
  "leadMagnet":{"badge":"Kostenlos","heading":"Kostenloses Mockup Ihres Merchs","desc":"Logo hochladen — wir legen es auf ein echtes Produkt und senden das Mockup an Ihre E-Mail.","emailLabel":"Ihre E-Mail","cta":"Mockup erhalten","loading":"Wird gesendet...","emailError":"Gültige E-Mail eingeben","success":"Danke!","successDesc":"Das Mockup kommt innerhalb von 24 Stunden","formLabel":"Mockup-Formular","orCalculate":"Möchten Sie den Preis jetzt?","openCalculator":"Preiskalkulator öffnen →"},
  "popup":{"badge":"Mobiler Popup-Service","heroHeading":"Merch-Popup auf Ihrer Veranstaltung —","heroSubheading":"ein Live-Erlebnis, das man nicht vergisst","heroDesc":"Wir kommen zu Ihnen. Gäste wählen Kleidung, personalisieren den Druck und nehmen fertigen Merch mit.","bookBtn":"Popup buchen","howItWorks":"So funktioniert's","nav":{"useCases":"Für wen","how":"So funktioniert's","faq":"FAQ","contacts":"Kontakt"},"book":"Buchen","footerCopyright":"U:DO CRAFT. Alle Rechte vorbehalten.","menuOpen":"Menü öffnen","menuClose":"Menü schließen","homeLink":"Startseite","stats":{"events":"Durchgeführte Popups","time":"Personalisierungszeit","guests":"Gäste pro Veranstaltung","satisfaction":"Zufriedene Veranstalter"},"useCases":{"label":"Für wen","heading":"Für jede Veranstaltung geeignet","items":{"corporate":{"title":"Firmenveranstaltungen","desc":"Events unvergesslich machen."},"conferences":{"title":"Konferenzen & Foren","desc":"Gebrandeter Merch — bestes Networking-Tool."},"festivals":{"title":"Festivals & Märkte","desc":"Popup-Stand der Aufmerksamkeit erregt."},"launches":{"title":"Produktlaunches","desc":"Launch mit selbstgemachtem Merch."},"universities":{"title":"Universitäten & Schulen","desc":"Abschlussfeiern, Open Days, Studentenevents."},"b2b":{"title":"B2B-Veranstaltungen","desc":"Partnertreffen, Messen, Präsentationen."}}},"process":{"label":"Ablauf","heading":"Drei Schritte zum perfekten Popup","steps":{"0":{"step":"01","title":"Format wählen","desc":"Veranstaltungsdetails mitteilen."},"1":{"step":"02","title":"Stand vorbereiten","desc":"Wir bringen Equipment und Kleidung."},"2":{"step":"03","title":"Gäste personalisieren","desc":"Jeder Gast wählt ein Produkt und nimmt fertigen Merch mit."}}},"faq":{"label":"FAQ","heading":"Häufig gestellte Fragen","items":{"0":{"q":"Mindestanzahl Teilnehmer?","a":"Ab 50 Personen."},"1":{"q":"Wie lange dauert die Personalisierung?","a":"3 bis 10 Minuten."},"2":{"q":"Welche Produkte gibt es?","a":"T-Shirts, Hoodies, Longsleeves, Caps."},"3":{"q":"Wer bezahlt?","a":"Beide Optionen möglich."},"4":{"q":"Wie weit im Voraus buchen?","a":"2–3 Wochen empfohlen."}}},"contact":{"label":"Buchen","heading":"Erzählen Sie von Ihrer Veranstaltung","desc":"Anfrage stellen — Antwort innerhalb eines Werktages.","benefits":{"0":"Kostenlose Beratung","1":"Individueller Kostenvoranschlag","2":"Antwort innerhalb 24 Stunden"}}}
})

# ── French ────────────────────────────────────────────────────────────────
save("fr", {
  "nav":{"catalog":"Catalogue","popup":"Popup","about":"À propos","how":"Comment ça marche","contacts":"Contact","startProject":"Démarrer un projet","openMenu":"Ouvrir le menu","closeMenu":"Fermer le menu","goToAccount":"Accéder au compte","signIn":"Se connecter","cartItems":"Panier — {count} articles","mainNav":"Navigation principale","logoLink":"U:DO CRAFT — retour à l'accueil"},
  "socialProof":{"trustedBy":"La confiance des équipes du monde entier"},
  "about":{"label":"À propos","heading":"Plateforme de","headingHighlight":"merchandising d'entreprise","desc1":"Des startups aux grandes entreprises — nous aidons les équipes à créer du merch dont elles sont fières.","desc2":"Dès 10 unités, sans frais cachés, production propre, chargé de compte personnel, garantie qualité.","features":{"editor":{"title":"Éditeur en ligne","desc":"Téléchargez votre logo, placez-le sur le produit et voyez le résultat immédiatement."},"minOrder":{"title":"Dès 10 unités","desc":"Parfait pour les startups et les petites équipes."},"pricing":{"title":"Tarification transparente","desc":"Facture immédiate. Aucun frais caché."},"timeline":{"title":"7–14 jours","desc":"De la confirmation à la livraison."},"quality":{"title":"Contrôle qualité","desc":"Chaque lot est inspecté avant expédition."},"manager":{"title":"Chargé de compte","desc":"Disponible de la première demande à la livraison."}}},
  "faq":{"heading":"Questions fréquentes","noAnswer":"Pas trouvé de réponse ?","contactUs":"Contactez-nous","replyTime":"— nous répondons sous une heure.","items":{"0":{"question":"Quelle est la quantité minimale ?","answer":"À partir de 10 unités."},"1":{"question":"Combien coûte l'impression ?","answer":"Le prix dépend du type et de la quantité. Visible dans l'éditeur en ligne."},"2":{"question":"Combien de temps prend une commande ?","answer":"7–14 jours ouvrables depuis la confirmation."},"3":{"question":"Puis-je voir la qualité avant ?","answer":"Oui. Box of Touch — échantillons physiques de tissus, couleurs et produits."},"4":{"question":"Et si le résultat ne me convient pas ?","answer":"On valide le design avant production. Si ça ne correspond pas — on refait gratuitement."},"5":{"question":"Y a-t-il des remises pour les grandes commandes ?","answer":"Oui. 10–49 unités — prix de base. 50–99 — -12%. 100+ — -15%."}}},
  "finalCta":{"ready":"Prêt à commencer ?","heading":"Votre merch — en 14 jours","desc":"De l'idée au produit fini. Éditeur en ligne, chargé de compte, garantie qualité.","cta":"Démarrer le projet","footer":"Dès 10 unités · Sans frais cachés · Livraison incluse"},
  "footer":{"readyToStart":"Prêt à commencer ?","readyDesc":"Dès 10 unités · 7–14 jours · Livraison","startProject":"Démarrer le projet","ariaLabel":"Pied de page","homeLink":"U:DO CRAFT — retour à l'accueil","columns":{"products":{"title":"Produits","links":{"constructor":"Configurateur de merch","catalog":"Catalogue","popup":"Stand popup","box":"Box of Touch","designer":"Recruter un designer"}},"company":{"title":"Entreprise","links":{"about":"À propos","how":"Comment ça marche","career":"Carrières","blog":"Blog"}},"support":{"title":"Assistance","links":{"faq":"FAQ","contact":"Contact","cabinet":"Compte","delivery":"Livraison et paiement"}}},"privacy":"Confidentialité","terms":"Conditions","cookies":"Cookies"},
  "cart":{"title":"Panier","titleWithCount":"Panier ({count})","empty":"Le panier est vide","emptyDesc":"Choisissez un produit et configurez l'impression","toCatalog":"Au catalogue","ariaLabel":"Panier","quantity":"{qty} pcs · {size}","total":"Total :","cartItem":"Article du panier"},
  "checkout":{"title":"Panier","orderTitle":"Passer commande","stepCart":"Panier","stepForm":"Données entreprise","emptyCart":"Le panier est vide","toCatalog":"Au catalogue","total":"Total","finalPriceNote":"Le prix final est convenu avec le chargé de compte","placeOrder":"Passer la commande","edit":"Modifier","discount":"-{pct}% remise","company":{"title":"Données entreprise","name":"Nom de l'entreprise *","namePlaceholder":"SARL «Nom»","taxId":"N° SIRET / TVA","taxIdPlaceholder":"FR12345678901"},"contact":{"title":"Personne de contact","fullName":"Prénom et nom *","fullNamePlaceholder":"Jean Dupont","email":"E-mail *","emailPlaceholder":"rh@entreprise.fr","phone":"Téléphone","phonePlaceholder":"+33 X XX XX XX XX","social":"Telegram / Instagram","socialPlaceholder":"@pseudo ou lien"},"delivery":{"title":"Livraison & délais","options":{"nova_poshta":{"label":"Colissimo","desc":"2–3 jours ouvrables"},"ukrposhta":{"label":"Chronopost","desc":"1–2 jours ouvrables"},"pickup":{"label":"Retrait","desc":"Sur rendez-vous"}},"deadline":"Date souhaitée","comment":"Commentaire","commentPlaceholder":"Souhaits particuliers..."},"submit":"Confirmer la commande","submitting":"Envoi en cours...","finalPriceManager":"Le prix final et la facture seront envoyés par le chargé de compte","success":{"title":"Commande reçue !","desc":"Notre chargé de compte vous contactera sous 24 heures.","createAccount":"Créer un compte personnel","loginAccount":"Se connecter au compte","createAccountDesc":"Suivez l'état de votre commande et consultez vos factures.","emailExists":"Cet e-mail est déjà enregistré. Entrez votre mot de passe pour vous connecter.","emailLabel":"E-mail","passwordLabel":"Mot de passe","newPasswordLabel":"Créer un mot de passe","passwordPlaceholder":"Minimum 6 caractères","enterPasswordPlaceholder":"Entrez le mot de passe","creating":"Création...","create":"Créer le compte","loggingIn":"Connexion...","login":"Se connecter","passwordError":"Le mot de passe doit comporter au moins 6 caractères","enterPasswordError":"Entrez le mot de passe","wrongPassword":"Mot de passe incorrect","registrationError":"Erreur d'inscription. Réessayez plus tard.","skip":"Ignorer, retour à l'accueil","accountCreated":{"title":"Compte créé !","desc":"Nous avons envoyé un e-mail de confirmation à {email}.","loginBtn":"Se connecter au compte","homeLink":"Retour à l'accueil"}},"back":"Retour","header":"U:DO","backAriaLabel":"Retour"},
  "cabinet":{"breadcrumb":"/ Compte","settings":"Paramètres","logout":"Se déconnecter","noOrders":"Aucune commande pour l'instant","toCatalog":"Au catalogue","writeTo":"Écrire au chargé de compte","tabs":{"details":"Détails","chat":"Chat","files":"Fichiers"},"status":{"new":"Nouvelle demande","in_progress":"En cours","production":"Production","completed":"Terminé","archived":"Archivé"},"delivery":{"nova_poshta":"Colissimo","ukrposhta":"Chronopost","pickup":"Retrait"},"details":{"phone":"Téléphone","email":"E-mail","company":"Entreprise","orderDate":"Date de commande","orderAmount":"Montant","delivery":"Livraison","deadline":"Délai","positions":"Positions ({n})","attachments":"Pièces jointes ({n})","invoice":"Télécharger la facture","print":"Impression"},"chat":{"placeholder":"Message...","sendLabel":"Envoyer","attachLabel":"Joindre un fichier","loading":"Chargement...","empty":"Pas encore de messages","fileTooLarge":"\"{name}\" dépasse 10 Mo"},"files":{"empty":"Pas encore de fichiers","openFile":"Ouvrir le fichier"}},
  "contactForm":{"nameLabel":"Votre nom *","namePlaceholder":"Jean Dupont","emailLabel":"E-mail *","emailPlaceholder":"rh@entreprise.fr","phoneLabel":"Téléphone *","phonePlaceholder":"+33 X XX XX XX XX","companyLabel":"Entreprise","companyPlaceholder":"Nom de l'entreprise","topicLabel":"Sujet *","messageLabel":"Parlez-nous de votre projet","messagePlaceholder":"Quantité, type de produit, délais...","filesLabel":"Télécharger des fichiers","filesClick":"Cliquez ou faites glisser des fichiers ici","filesDesc":"Maquettes, logos, images...","submit":"Envoyer","submitting":"Envoi en cours...","error":"Une erreur s'est produite. Réessayez.","success":"Merci de nous avoir contactés !","successDesc":"Nous avons reçu votre demande.","deleteFile":"Supprimer {name}","topics":{"merch":{"label":"Merch d'entreprise","desc":"T-shirts, sweats, accessoires"},"popup":{"label":"Stand popup pour événement","desc":"Personnalisation live"},"box":{"label":"Box of Touch","desc":"Échantillons physiques avant production"},"designer":{"label":"Services de design","desc":"Développement ou adaptation de logo"},"bulk":{"label":"Grande commande (500+)","desc":"Commandes en gros"},"other":{"label":"Autre","desc":"Toute autre question"}}},
  "privacy":{"title":"Politique de confidentialité","noContent":"Contenu pas encore ajouté."},
  "terms":{"title":"Conditions d'utilisation","noContent":"Contenu pas encore ajouté."},
  "order":{"loadError":"Impossible de charger le catalogue. Veuillez actualiser."},
  "leadMagnet":{"badge":"Gratuit","heading":"Obtenez un mockup gratuit de votre merch","desc":"Téléchargez votre logo — nous l'appliquons sur un vrai produit et envoyons le mockup.","emailLabel":"Votre e-mail","cta":"Obtenir le mockup","loading":"Envoi...","emailError":"Entrez un e-mail valide","success":"Merci !","successDesc":"Le mockup arrivera dans votre boîte mail sous 24 h","formLabel":"Formulaire de mockup","orCalculate":"Vous voulez connaître le prix ?","openCalculator":"Ouvrir le calculateur →"},
  "popup":{"badge":"Service popup mobile","heroHeading":"Popup merch lors de votre événement —","heroSubheading":"une expérience live qu'on n'oublie pas","heroDesc":"Nous venons chez vous. Les invités personnalisent sur place et repartent avec leur merch.","bookBtn":"Réserver un popup","howItWorks":"Comment ça marche","nav":{"useCases":"Pour qui","how":"Comment ça marche","faq":"FAQ","contacts":"Contact"},"book":"Réserver","footerCopyright":"U:DO CRAFT. Tous droits réservés.","menuOpen":"Ouvrir le menu","menuClose":"Fermer le menu","homeLink":"Accueil","stats":{"events":"Popups réalisés","time":"Temps de personnalisation","guests":"Invités par événement","satisfaction":"Organisateurs satisfaits"},"useCases":{"label":"Pour qui","heading":"Adapté à tout événement","items":{"corporate":{"title":"Événements d'entreprise","desc":"Rendre l'événement inoubliable."},"conferences":{"title":"Conférences & forums","desc":"Merch brandé sur place."},"festivals":{"title":"Festivals & marchés","desc":"Stand popup qui attire l'attention."},"launches":{"title":"Lancements produits","desc":"Lancement avec merch créé par les invités."},"universities":{"title":"Universités & écoles","desc":"Remises de diplômes, portes ouvertes."},"b2b":{"title":"Événements B2B","desc":"Réunions partenaires, salons."}}},"process":{"label":"Processus","heading":"Trois étapes vers le popup parfait","steps":{"0":{"step":"01","title":"Choisir le format","desc":"Parlez-nous de l'événement."},"1":{"step":"02","title":"Préparer le stand","desc":"Nous apportons tout le nécessaire."},"2":{"step":"03","title":"Les invités personnalisent","desc":"Chaque invité repart avec son merch."}}},"faq":{"label":"FAQ","heading":"Questions fréquentes","items":{"0":{"q":"Combien de participants minimum ?","a":"À partir de 50 personnes."},"1":{"q":"Temps par produit ?","a":"De 3 à 10 minutes."},"2":{"q":"Quels produits ?","a":"T-shirts, sweats, manches longues, casquettes."},"3":{"q":"Qui paye ?","a":"Les deux options sont possibles."},"4":{"q":"Délai de réservation ?","a":"2–3 semaines recommandées."}}},"contact":{"label":"Réserver","heading":"Parlez-nous de votre événement","desc":"Laissez une demande — réponse sous un jour ouvrable.","benefits":{"0":"Consultation gratuite","1":"Estimation personnalisée","2":"Réponse sous 24 heures"}}}
})

# ── Spanish ───────────────────────────────────────────────────────────────
save("es", {
  "nav":{"catalog":"Catálogo","popup":"Popup","about":"Nosotros","how":"Cómo funciona","contacts":"Contacto","startProject":"Iniciar proyecto","openMenu":"Abrir menú","closeMenu":"Cerrar menú","goToAccount":"Ir a la cuenta","signIn":"Iniciar sesión","cartItems":"Carrito — {count} artículos"},
  "socialProof":{"trustedBy":"La confianza de equipos de todo el mundo"},
  "about":{"label":"Nosotros","heading":"Plataforma de","headingHighlight":"merchandising corporativo","desc1":"De startups a grandes corporaciones — ayudamos a los equipos a crear merch del que se enorgullezcan.","desc2":"Desde 10 unidades, sin cargos ocultos, producción propia, gestor personal, garantía de calidad.","features":{"editor":{"title":"Editor online","desc":"Sube tu logo, colócalo en el producto y ve el resultado al instante."},"minOrder":{"title":"Desde 10 unidades","desc":"Perfecto para startups y equipos pequeños."},"pricing":{"title":"Precio transparente","desc":"Factura inmediata. Sin cargos ocultos."},"timeline":{"title":"7–14 días","desc":"De la confirmación a la entrega."},"quality":{"title":"Control de calidad","desc":"Cada lote se inspecciona antes del envío."},"manager":{"title":"Gestor personal","desc":"Disponible desde la primera consulta hasta la entrega."}}},
  "faq":{"heading":"Preguntas frecuentes","noAnswer":"¿No encontraste respuesta?","contactUs":"Contáctanos","replyTime":"— respondemos en una hora.","items":{"0":{"question":"¿Cuál es el pedido mínimo?","answer":"Desde 10 unidades."},"1":{"question":"¿Cuánto cuesta la impresión?","answer":"El precio depende del tipo y la cantidad. Véalo en el editor online."},"2":{"question":"¿Cuánto tarda el pedido?","answer":"Plazo estándar — 7–14 días hábiles desde la confirmación."},"3":{"question":"¿Puedo ver la calidad antes?","answer":"Sí. Box of Touch — muestras físicas de telas, colores y productos."},"4":{"question":"¿Qué pasa si no me gusta?","answer":"Aprobamos el diseño antes de la producción. Si no coincide — lo rehacemos gratis."},"5":{"question":"¿Hay descuentos para pedidos grandes?","answer":"Sí. 10–49 — precio base. 50–99 — 12% dto. 100+ — 15% dto."}}},
  "finalCta":{"ready":"¿Listo para empezar?","heading":"Tu merch — en 14 días","desc":"De la idea al producto terminado. Editor online, gestor personal, garantía de calidad.","cta":"Iniciar proyecto","footer":"Desde 10 unidades · Sin cargos ocultos · Envío incluido"},
  "footer":{"readyToStart":"¿Listo para empezar?","readyDesc":"Desde 10 unidades · 7–14 días · Envío","startProject":"Iniciar proyecto","ariaLabel":"Pie de página","homeLink":"U:DO CRAFT — volver al inicio","columns":{"products":{"title":"Productos","links":{"constructor":"Configurador de merch","catalog":"Catálogo","popup":"Expositor popup","box":"Box of Touch","designer":"Contratar diseñador"}},"company":{"title":"Empresa","links":{"about":"Nosotros","how":"Cómo funciona","career":"Empleo","blog":"Blog"}},"support":{"title":"Soporte","links":{"faq":"FAQ","contact":"Contacto","cabinet":"Cuenta","delivery":"Envío y pago"}}},"privacy":"Privacidad","terms":"Términos","cookies":"Cookies"},
  "cart":{"title":"Carrito","titleWithCount":"Carrito ({count})","empty":"El carrito está vacío","emptyDesc":"Elige un producto y configura la impresión","toCatalog":"Al catálogo","ariaLabel":"Carrito","quantity":"{qty} uds · {size}","total":"Total:","cartItem":"Artículo del carrito"},
  "checkout":{"title":"Carrito","orderTitle":"Realizar pedido","stepCart":"Carrito","stepForm":"Datos de empresa","emptyCart":"El carrito está vacío","toCatalog":"Al catálogo","total":"Total","finalPriceNote":"El precio final se acuerda con el gestor","placeOrder":"Realizar el pedido","edit":"Editar","discount":"-{pct}% descuento","company":{"title":"Datos de empresa","name":"Nombre de la empresa *","namePlaceholder":"SL «Nombre»","taxId":"NIF / CIF","taxIdPlaceholder":"B12345678"},"contact":{"title":"Persona de contacto","fullName":"Nombre y apellidos *","fullNamePlaceholder":"Juan García","email":"Correo electrónico *","emailPlaceholder":"rrhh@empresa.es","phone":"Teléfono","phonePlaceholder":"+34 XXX XXX XXX","social":"Telegram / Instagram","socialPlaceholder":"@usuario o enlace"},"delivery":{"title":"Envío y plazos","options":{"nova_poshta":{"label":"Correos","desc":"3–5 días hábiles"},"ukrposhta":{"label":"MRW","desc":"1–2 días hábiles"},"pickup":{"label":"Recogida","desc":"Previa cita"}},"deadline":"Fecha deseada","comment":"Comentario del pedido","commentPlaceholder":"Deseos especiales..."},"submit":"Confirmar pedido","submitting":"Enviando...","finalPriceManager":"El precio final y la factura serán enviados por el gestor","success":{"title":"¡Pedido recibido!","desc":"Nuestro gestor se pondrá en contacto contigo en 24 horas.","createAccount":"Crear cuenta personal","loginAccount":"Acceder a la cuenta","createAccountDesc":"Sigue el estado de tu pedido y consulta facturas.","emailExists":"Este correo ya está registrado.","emailLabel":"Correo electrónico","passwordLabel":"Contraseña","newPasswordLabel":"Crea una contraseña","passwordPlaceholder":"Mínimo 6 caracteres","enterPasswordPlaceholder":"Introduce la contraseña","creating":"Creando...","create":"Crear cuenta","loggingIn":"Accediendo...","login":"Acceder","passwordError":"La contraseña debe tener al menos 6 caracteres","enterPasswordError":"Introduce la contraseña","wrongPassword":"Contraseña incorrecta","registrationError":"Error de registro. Inténtalo más tarde.","skip":"Omitir, volver al inicio","accountCreated":{"title":"¡Cuenta creada!","desc":"Enviamos un correo de confirmación a {email}.","loginBtn":"Acceder a la cuenta","homeLink":"Volver al inicio"}},"back":"Atrás","header":"U:DO","backAriaLabel":"Atrás"},
  "cabinet":{"breadcrumb":"/ Cuenta","settings":"Configuración","logout":"Cerrar sesión","noOrders":"Aún no hay pedidos","toCatalog":"Al catálogo","writeTo":"Escribir al gestor","tabs":{"details":"Detalles","chat":"Chat","files":"Archivos"},"status":{"new":"Nueva solicitud","in_progress":"En proceso","production":"Producción","completed":"Completado","archived":"Archivado"},"delivery":{"nova_poshta":"Correos","ukrposhta":"MRW","pickup":"Recogida"},"details":{"phone":"Teléfono","email":"Correo","company":"Empresa","orderDate":"Fecha del pedido","orderAmount":"Importe","delivery":"Envío","deadline":"Plazo","positions":"Posiciones ({n})","attachments":"Adjuntos ({n})","invoice":"Descargar factura","print":"Impresión"},"chat":{"placeholder":"Mensaje...","sendLabel":"Enviar","attachLabel":"Adjuntar archivo","loading":"Cargando...","empty":"Aún no hay mensajes","fileTooLarge":"\"{name}\" supera los 10 MB"},"files":{"empty":"Aún no hay archivos","openFile":"Abrir archivo"}},
  "contactForm":{"nameLabel":"Tu nombre *","namePlaceholder":"Juan García","emailLabel":"Correo electrónico *","emailPlaceholder":"rrhh@empresa.es","phoneLabel":"Teléfono *","phonePlaceholder":"+34 XXX XXX XXX","companyLabel":"Empresa","companyPlaceholder":"Nombre de la empresa","topicLabel":"Asunto *","messageLabel":"Cuéntanos sobre tu proyecto","messagePlaceholder":"Cantidad, tipo de producto, plazos...","filesLabel":"Subir archivos","filesClick":"Haz clic o arrastra archivos aquí","filesDesc":"Diseños, logos, imágenes...","submit":"Enviar","submitting":"Enviando...","error":"Ocurrió un error. Inténtalo de nuevo.","success":"¡Gracias por contactarnos!","successDesc":"Recibimos tu solicitud.","deleteFile":"Eliminar {name}","topics":{"merch":{"label":"Merch corporativo","desc":"Camisetas, sudaderas, accesorios"},"popup":{"label":"Expositor popup","desc":"Personalización en vivo"},"box":{"label":"Box of Touch","desc":"Muestras físicas antes de la producción"},"designer":{"label":"Servicios de diseño","desc":"Desarrollo o adaptación de logotipos"},"bulk":{"label":"Pedido grande (500+)","desc":"Pedidos al por mayor"},"other":{"label":"Otro","desc":"Cualquier otra pregunta"}}},
  "privacy":{"title":"Política de privacidad","noContent":"Contenido no añadido todavía."},
  "terms":{"title":"Términos y condiciones","noContent":"Contenido no añadido todavía."},
  "order":{"loadError":"No se pudo cargar el catálogo. Por favor, recarga la página."},
  "leadMagnet":{"badge":"Gratis","heading":"Consigue un mockup gratuito de tu merch","desc":"Sube tu logo — lo aplicamos y te enviamos el mockup por correo.","emailLabel":"Tu correo","cta":"Obtener mockup","loading":"Enviando...","emailError":"Introduce un correo válido","success":"¡Gracias!","successDesc":"El mockup llegará en 24 h","formLabel":"Formulario de mockup","orCalculate":"¿Quieres saber el precio ahora?","openCalculator":"Abrir calculadora →"},
  "popup":{"badge":"Servicio popup móvil","heroHeading":"Popup de merch en tu evento —","heroSubheading":"una experiencia en vivo que se recuerda","heroDesc":"Vamos a tu evento. Los invitados personalizan in situ y se van con su merch.","bookBtn":"Reservar popup","howItWorks":"Cómo funciona","nav":{"useCases":"Para quién","how":"Cómo funciona","faq":"FAQ","contacts":"Contacto"},"book":"Reservar","footerCopyright":"U:DO CRAFT. Todos los derechos reservados.","menuOpen":"Abrir menú","menuClose":"Cerrar menú","homeLink":"Inicio","stats":{"events":"Popups realizados","time":"Tiempo de personalización","guests":"Invitados por evento","satisfaction":"Organizadores satisfechos"},"useCases":{"label":"Para quién","heading":"Adecuado para cualquier evento","items":{"corporate":{"title":"Eventos corporativos","desc":"Haz el evento inolvidable."},"conferences":{"title":"Conferencias y foros","desc":"Merch con marca in situ."},"festivals":{"title":"Festivales y mercados","desc":"Stand popup que atrae atención."},"launches":{"title":"Lanzamientos de producto","desc":"Lanzamiento con merch propio."},"universities":{"title":"Universidades y escuelas","desc":"Graduaciones, jornadas, eventos."},"b2b":{"title":"Eventos B2B","desc":"Reuniones, ferias, presentaciones."}}},"process":{"label":"Proceso","heading":"Tres pasos hacia el popup perfecto","steps":{"0":{"step":"01","title":"Elegir el formato","desc":"Cuéntanos sobre el evento."},"1":{"step":"02","title":"Preparar el stand","desc":"Llevamos todo lo necesario."},"2":{"step":"03","title":"Los invitados personalizan","desc":"Cada invitado se va con su merch."}}},"faq":{"label":"FAQ","heading":"Preguntas frecuentes","items":{"0":{"q":"¿Cuántos participantes mínimo?","a":"Desde 50 personas."},"1":{"q":"¿Cuánto tarda la personalización?","a":"De 3 a 10 minutos."},"2":{"q":"¿Qué productos hay?","a":"Camisetas, sudaderas, gorras, accesorios."},"3":{"q":"¿Quién paga?","a":"Ambas opciones son posibles."},"4":{"q":"¿Con cuánta antelación reservar?","a":"2–3 semanas antes."}}},"contact":{"label":"Reservar","heading":"Cuéntanos sobre tu evento","desc":"Deja una solicitud — respuesta en un día hábil.","benefits":{"0":"Consulta gratuita","1":"Presupuesto individualizado","2":"Respuesta en 24 horas"}}}
})

# ── Italian ───────────────────────────────────────────────────────────────
save("it", {
  "nav":{"catalog":"Catalogo","popup":"Popup","about":"Chi siamo","how":"Come funziona","contacts":"Contatti","startProject":"Avvia progetto","openMenu":"Apri menu","closeMenu":"Chiudi menu","goToAccount":"Vai all'account","signIn":"Accedi","cartItems":"Carrello — {count} articoli"},
  "socialProof":{"trustedBy":"La fiducia dei team di tutto il mondo"},
  "about":{"label":"Chi siamo","heading":"Piattaforma di","headingHighlight":"merchandising aziendale","desc1":"Da startup a grandi aziende — aiutiamo i team a creare merch di cui andare fieri.","desc2":"Da 10 pezzi, senza costi nascosti, produzione propria, account manager personale, garanzia qualità.","features":{"editor":{"title":"Editor online","desc":"Carica il logo, posizionalo e vedi subito il risultato."},"minOrder":{"title":"Da 10 pezzi","desc":"Perfetto per startup e piccoli team."},"pricing":{"title":"Prezzi trasparenti","desc":"Fattura immediata. Nessun costo nascosto."},"timeline":{"title":"7–14 giorni","desc":"Dalla conferma alla consegna."},"quality":{"title":"Controllo qualità","desc":"Ogni lotto viene ispezionato prima della spedizione."},"manager":{"title":"Account manager","desc":"Disponibile dalla prima richiesta alla consegna."}}},
  "faq":{"heading":"Domande frequenti","noAnswer":"Non hai trovato risposta?","contactUs":"Contattaci","replyTime":"— rispondiamo entro un'ora.","items":{"0":{"question":"Qual è la quantità minima?","answer":"Da 10 pezzi. Nessun sovrapprezzo."},"1":{"question":"Quanto costa la stampa?","answer":"Il prezzo dipende dal tipo e dalla quantità. Visibile nell'editor."},"2":{"question":"Quanto tempo richiede un ordine?","answer":"7–14 giorni lavorativi dalla conferma."},"3":{"question":"Posso vedere la qualità prima?","answer":"Sì. Box of Touch — campioni fisici di tessuti, colori e prodotti."},"4":{"question":"E se il risultato non mi piace?","answer":"Approviamo il design prima della produzione. Se non corrisponde — rifacciamo gratuitamente."},"5":{"question":"Ci sono sconti per ordini grandi?","answer":"Sì. 10–49 pz — prezzo base. 50–99 — 12%. 100+ — 15%."}}},
  "finalCta":{"ready":"Pronto per iniziare?","heading":"Il tuo merch — in 14 giorni","desc":"Dall'idea al prodotto finito. Editor online, account manager, garanzia qualità.","cta":"Avvia progetto","footer":"Da 10 pezzi · Senza costi nascosti · Spedizione inclusa"},
  "footer":{"readyToStart":"Pronto per iniziare?","readyDesc":"Da 10 pezzi · 7–14 giorni · Spedizione","startProject":"Avvia progetto","ariaLabel":"Piè di pagina","homeLink":"U:DO CRAFT — torna alla home","columns":{"products":{"title":"Prodotti","links":{"constructor":"Configuratore merch","catalog":"Catalogo","popup":"Stand popup","box":"Box of Touch","designer":"Assumi designer"}},"company":{"title":"Azienda","links":{"about":"Chi siamo","how":"Come funziona","career":"Lavora con noi","blog":"Blog"}},"support":{"title":"Supporto","links":{"faq":"FAQ","contact":"Contatti","cabinet":"Account","delivery":"Spedizione e pagamento"}}},"privacy":"Privacy","terms":"Termini","cookies":"Cookie"},
  "cart":{"title":"Carrello","titleWithCount":"Carrello ({count})","empty":"Il carrello è vuoto","emptyDesc":"Scegli un prodotto e configura la stampa","toCatalog":"Al catalogo","ariaLabel":"Carrello","quantity":"{qty} pz · {size}","total":"Totale:","cartItem":"Articolo nel carrello"},
  "checkout":{"title":"Carrello","orderTitle":"Effettua ordine","stepCart":"Carrello","stepForm":"Dati azienda","emptyCart":"Il carrello è vuoto","toCatalog":"Al catalogo","total":"Totale","finalPriceNote":"Il prezzo finale viene concordato con l'account manager","placeOrder":"Effettua ordine","edit":"Modifica","discount":"-{pct}% sconto","company":{"title":"Dati azienda","name":"Nome azienda *","namePlaceholder":"Srl «Nome»","taxId":"P.IVA","taxIdPlaceholder":"IT12345678901"},"contact":{"title":"Persona di contatto","fullName":"Nome e cognome *","fullNamePlaceholder":"Mario Rossi","email":"E-mail *","emailPlaceholder":"hr@azienda.it","phone":"Telefono","phonePlaceholder":"+39 XXX XXX XXXX","social":"Telegram / Instagram","socialPlaceholder":"@username o link"},"delivery":{"title":"Spedizione e scadenze","options":{"nova_poshta":{"label":"Poste Italiane","desc":"3–5 giorni lavorativi"},"ukrposhta":{"label":"DHL","desc":"1–2 giorni lavorativi"},"pickup":{"label":"Ritiro","desc":"Su appuntamento"}},"deadline":"Data desiderata","comment":"Note ordine","commentPlaceholder":"Desideri particolari..."},"submit":"Conferma ordine","submitting":"Invio in corso...","finalPriceManager":"Prezzo finale e fattura inviati dall'account manager","success":{"title":"Ordine ricevuto!","desc":"Il nostro account manager ti contatterà entro 24 ore.","createAccount":"Crea account personale","loginAccount":"Accedi all'account","createAccountDesc":"Tieni traccia del tuo ordine e consulta le fatture.","emailExists":"Questa e-mail è già registrata.","emailLabel":"E-mail","passwordLabel":"Password","newPasswordLabel":"Crea una password","passwordPlaceholder":"Minimo 6 caratteri","enterPasswordPlaceholder":"Inserisci la password","creating":"Creazione...","create":"Crea account","loggingIn":"Accesso...","login":"Accedi","passwordError":"La password deve avere almeno 6 caratteri","enterPasswordError":"Inserisci la password","wrongPassword":"Password errata","registrationError":"Errore di registrazione. Riprova più tardi.","skip":"Salta, torna alla home","accountCreated":{"title":"Account creato!","desc":"Abbiamo inviato una conferma a {email}.","loginBtn":"Accedi all'account","homeLink":"Torna alla home"}},"back":"Indietro","header":"U:DO","backAriaLabel":"Indietro"},
  "cabinet":{"breadcrumb":"/ Account","settings":"Impostazioni","logout":"Esci","noOrders":"Ancora nessun ordine","toCatalog":"Al catalogo","writeTo":"Scrivi all'account manager","tabs":{"details":"Dettagli","chat":"Chat","files":"File"},"status":{"new":"Nuova richiesta","in_progress":"In lavorazione","production":"Produzione","completed":"Completato","archived":"Archiviato"},"delivery":{"nova_poshta":"Poste Italiane","ukrposhta":"DHL","pickup":"Ritiro"},"details":{"phone":"Telefono","email":"E-mail","company":"Azienda","orderDate":"Data ordine","orderAmount":"Importo","delivery":"Spedizione","deadline":"Scadenza","positions":"Posizioni ({n})","attachments":"Allegati ({n})","invoice":"Scarica fattura","print":"Stampa"},"chat":{"placeholder":"Messaggio...","sendLabel":"Invia","attachLabel":"Allega file","loading":"Caricamento...","empty":"Ancora nessun messaggio","fileTooLarge":"\"{name}\" supera 10 MB"},"files":{"empty":"Ancora nessun file","openFile":"Apri file"}},
  "contactForm":{"nameLabel":"Il tuo nome *","namePlaceholder":"Mario Rossi","emailLabel":"E-mail *","emailPlaceholder":"hr@azienda.it","phoneLabel":"Telefono *","phonePlaceholder":"+39 XXX XXX XXXX","companyLabel":"Azienda","companyPlaceholder":"Nome dell'azienda","topicLabel":"Oggetto *","messageLabel":"Raccontaci del tuo progetto","messagePlaceholder":"Quantità, tipo, scadenze...","filesLabel":"Carica file","filesClick":"Clicca o trascina i file qui","filesDesc":"Design, loghi, immagini...","submit":"Invia","submitting":"Invio in corso...","error":"Si è verificato un errore. Riprova.","success":"Grazie per averci contattato!","successDesc":"Abbiamo ricevuto la tua richiesta.","deleteFile":"Elimina {name}","topics":{"merch":{"label":"Merch aziendale","desc":"T-shirt, felpe, accessori"},"popup":{"label":"Stand popup per eventi","desc":"Personalizzazione dal vivo"},"box":{"label":"Box of Touch","desc":"Campioni fisici prima della produzione"},"designer":{"label":"Servizi di design","desc":"Sviluppo o adattamento loghi"},"bulk":{"label":"Ordine grande (500+)","desc":"Ordini all'ingrosso"},"other":{"label":"Altro","desc":"Qualsiasi altra domanda"}}},
  "privacy":{"title":"Informativa sulla privacy","noContent":"Contenuto non ancora aggiunto."},
  "terms":{"title":"Termini e condizioni","noContent":"Contenuto non ancora aggiunto."},
  "order":{"loadError":"Impossibile caricare il catalogo. Aggiorna la pagina."},
  "leadMagnet":{"badge":"Gratuito","heading":"Ottieni un mockup gratuito del tuo merch","desc":"Carica il logo — lo applichiamo e inviamo il mockup alla tua email.","emailLabel":"La tua email","cta":"Ottieni mockup","loading":"Invio...","emailError":"Inserisci un'email valida","success":"Grazie!","successDesc":"Il mockup arriverà entro 24 ore","formLabel":"Modulo mockup","orCalculate":"Vuoi sapere il prezzo adesso?","openCalculator":"Apri il calcolatore →"},
  "popup":{"badge":"Servizio popup mobile","heroHeading":"Popup merch al tuo evento —","heroSubheading":"un'esperienza dal vivo che si ricorda","heroDesc":"Veniamo da te. Gli ospiti personalizzano sul posto e ripartono con il loro merch.","bookBtn":"Prenota un popup","howItWorks":"Come funziona","nav":{"useCases":"Per chi","how":"Come funziona","faq":"FAQ","contacts":"Contatti"},"book":"Prenota","footerCopyright":"U:DO CRAFT. Tutti i diritti riservati.","menuOpen":"Apri menu","menuClose":"Chiudi menu","homeLink":"Home","stats":{"events":"Popup realizzati","time":"Tempo di personalizzazione","guests":"Ospiti per evento","satisfaction":"Organizzatori soddisfatti"},"useCases":{"label":"Per chi","heading":"Adatto a qualsiasi evento","items":{"corporate":{"title":"Eventi aziendali","desc":"Rendi l'evento indimenticabile."},"conferences":{"title":"Conferenze e forum","desc":"Merch brandizzato in loco."},"festivals":{"title":"Festival e mercati","desc":"Stand che attira l'attenzione."},"launches":{"title":"Lanci di prodotto","desc":"Lancio con merch creato dagli ospiti."},"universities":{"title":"Università e scuole","desc":"Lauree, open day, eventi studenteschi."},"b2b":{"title":"Eventi B2B","desc":"Incontri partner, fiere, presentazioni."}}},"process":{"label":"Processo","heading":"Tre passi verso il popup perfetto","steps":{"0":{"step":"01","title":"Scegli il formato","desc":"Raccontaci dell'evento."},"1":{"step":"02","title":"Prepariamo lo stand","desc":"Portiamo tutto il necessario."},"2":{"step":"03","title":"Gli ospiti personalizzano","desc":"Ogni ospite riparte con il suo merch."}}},"faq":{"label":"FAQ","heading":"Domande frequenti","items":{"0":{"q":"Quanti partecipanti minimi?","a":"Da 50 persone."},"1":{"q":"Tempo per personalizzare?","a":"Da 3 a 10 minuti."},"2":{"q":"Quali prodotti?","a":"T-shirt, felpe, maniche lunghe, cappellini."},"3":{"q":"Chi paga?","a":"Entrambe le opzioni sono possibili."},"4":{"q":"Con quanto anticipo prenotare?","a":"2–3 settimane prima."}}},"contact":{"label":"Prenota","heading":"Raccontaci del tuo evento","desc":"Lascia una richiesta — risposta entro un giorno lavorativo.","benefits":{"0":"Consulenza gratuita","1":"Preventivo personalizzato","2":"Risposta entro 24 ore"}}}
})

# ── Polish ────────────────────────────────────────────────────────────────
save("pl", {
  "nav":{"catalog":"Katalog","popup":"Popup","about":"O nas","how":"Jak to działa","contacts":"Kontakt","startProject":"Rozpocznij projekt","openMenu":"Otwórz menu","closeMenu":"Zamknij menu","goToAccount":"Przejdź do konta","signIn":"Zaloguj się","cartItems":"Koszyk — {count} produktów"},
  "socialProof":{"trustedBy":"Zaufanie zespołów z całego świata"},
  "about":{"label":"O nas","heading":"Platforma","headingHighlight":"merchandisingu korporacyjnego","desc1":"Od startupów po duże korporacje — pomagamy zespołom tworzyć merch, z którego są dumne.","desc2":"Od 10 sztuk, bez ukrytych opłat, własna produkcja, osobisty opiekun, gwarancja jakości.","features":{"editor":{"title":"Edytor online","desc":"Prześlij logo, umieść na produkcie i od razu zobaczysz efekt."},"minOrder":{"title":"Od 10 sztuk","desc":"Idealne dla startupów i małych zespołów."},"pricing":{"title":"Przejrzyste ceny","desc":"Faktura od razu. Żadnych ukrytych opłat."},"timeline":{"title":"7–14 dni","desc":"Od potwierdzenia do dostawy."},"quality":{"title":"Kontrola jakości","desc":"Każda partia jest sprawdzana przed wysyłką."},"manager":{"title":"Osobisty opiekun","desc":"Dostępny od pierwszego zapytania do odbioru."}}},
  "faq":{"heading":"Często zadawane pytania","noAnswer":"Nie znalazłeś odpowiedzi?","contactUs":"Napisz do nas","replyTime":"— odpiszemy w ciągu godziny.","items":{"0":{"question":"Jaka jest minimalna ilość zamówienia?","answer":"Od 10 sztuk. Brak dopłaty za małe partie."},"1":{"question":"Ile kosztuje nadruk?","answer":"Cena zależy od rodzaju (sitodruk, haft, DTF) i ilości."},"2":{"question":"Jak długo trwa realizacja zamówienia?","answer":"Standardowy czas — 7–14 dni roboczych od potwierdzenia."},"3":{"question":"Czy mogę zobaczyć jakość przed dużą partią?","answer":"Tak. Box of Touch — fizyczne próbki tkanin, kolorów i produktów."},"4":{"question":"Co jeśli nie spodoba mi się wynik?","answer":"Zatwierdzamy projekt przed produkcją. Jeśli produkt nie odpowiada — przerabiamy za darmo."},"5":{"question":"Czy są zniżki przy dużych zamówieniach?","answer":"Tak. 10–49 sztuk — cena bazowa. 50–99 — rabat 12%. 100+ — rabat 15%."}}},
  "finalCta":{"ready":"Gotowy do startu?","heading":"Twój merch — w 14 dni","desc":"Od pomysłu do gotowego produktu. Edytor online, osobisty opiekun, gwarancja jakości.","cta":"Rozpocznij projekt","footer":"Od 10 sztuk · Bez ukrytych opłat · Dostawa w cenie"},
  "footer":{"readyToStart":"Gotowy do startu?","readyDesc":"Od 10 sztuk · 7–14 dni · Dostawa","startProject":"Rozpocznij projekt","ariaLabel":"Stopka","homeLink":"U:DO CRAFT — powrót na stronę główną","columns":{"products":{"title":"Produkty","links":{"constructor":"Konfigurator merchu","catalog":"Katalog","popup":"Stoisko popup","box":"Box of Touch","designer":"Zatrudnij projektanta"}},"company":{"title":"Firma","links":{"about":"O nas","how":"Jak to działa","career":"Kariera","blog":"Blog"}},"support":{"title":"Wsparcie","links":{"faq":"FAQ","contact":"Kontakt","cabinet":"Konto","delivery":"Wysyłka i płatność"}}},"privacy":"Prywatność","terms":"Regulamin","cookies":"Pliki cookie"},
  "cart":{"title":"Koszyk","titleWithCount":"Koszyk ({count})","empty":"Koszyk jest pusty","emptyDesc":"Wybierz produkt i skonfiguruj nadruk","toCatalog":"Do katalogu","ariaLabel":"Koszyk","quantity":"{qty} szt · {size}","total":"Łącznie:","cartItem":"Produkt w koszyku"},
  "checkout":{"title":"Koszyk","orderTitle":"Złóż zamówienie","stepCart":"Koszyk","stepForm":"Dane firmy","emptyCart":"Koszyk jest pusty","toCatalog":"Do katalogu","total":"Łącznie","finalPriceNote":"Cena finalna jest ustalana z opiekunem","placeOrder":"Złóż zamówienie","edit":"Edytuj","discount":"-{pct}% rabat","company":{"title":"Dane firmy","name":"Nazwa firmy *","namePlaceholder":"Sp. z o.o. «Nazwa»","taxId":"NIP / REGON","taxIdPlaceholder":"1234567890"},"contact":{"title":"Osoba kontaktowa","fullName":"Imię i nazwisko *","fullNamePlaceholder":"Jan Kowalski","email":"E-mail *","emailPlaceholder":"hr@firma.pl","phone":"Telefon","phonePlaceholder":"+48 XXX XXX XXX","social":"Telegram / Instagram","socialPlaceholder":"@użytkownik lub link"},"delivery":{"title":"Dostawa i terminy","options":{"nova_poshta":{"label":"DPD","desc":"2–3 dni robocze"},"ukrposhta":{"label":"Poczta Polska","desc":"3–5 dni roboczych"},"pickup":{"label":"Odbiór własny","desc":"Po uzgodnieniu"}},"deadline":"Pożądana data","comment":"Komentarz do zamówienia","commentPlaceholder":"Szczególne życzenia..."},"submit":"Potwierdź zamówienie","submitting":"Wysyłanie...","finalPriceManager":"Cena finalna i faktura zostaną przesłane przez opiekuna","success":{"title":"Zamówienie przyjęte!","desc":"Nasz opiekun skontaktuje się z Tobą w ciągu 24 godzin.","createAccount":"Utwórz konto osobiste","loginAccount":"Zaloguj się do konta","createAccountDesc":"Śledź status zamówienia i przeglądaj faktury.","emailExists":"Ten e-mail jest już zarejestrowany.","emailLabel":"E-mail","passwordLabel":"Hasło","newPasswordLabel":"Utwórz hasło","passwordPlaceholder":"Minimum 6 znaków","enterPasswordPlaceholder":"Podaj hasło","creating":"Tworzenie...","create":"Utwórz konto","loggingIn":"Logowanie...","login":"Zaloguj się","passwordError":"Hasło musi mieć co najmniej 6 znaków","enterPasswordError":"Podaj hasło","wrongPassword":"Nieprawidłowe hasło","registrationError":"Błąd rejestracji. Spróbuj później.","skip":"Pomiń, wróć na stronę główną","accountCreated":{"title":"Konto utworzone!","desc":"Wysłaliśmy e-mail potwierdzający na adres {email}.","loginBtn":"Zaloguj się do konta","homeLink":"Wróć na stronę główną"}},"back":"Wstecz","header":"U:DO","backAriaLabel":"Wstecz"},
  "cabinet":{"breadcrumb":"/ Konto","settings":"Ustawienia","logout":"Wyloguj","noOrders":"Brak zamówień","toCatalog":"Do katalogu","writeTo":"Napisz do opiekuna","tabs":{"details":"Szczegóły","chat":"Chat","files":"Pliki"},"status":{"new":"Nowe zgłoszenie","in_progress":"W trakcie","production":"Produkcja","completed":"Zakończone","archived":"Archiwum"},"delivery":{"nova_poshta":"DPD","ukrposhta":"Poczta Polska","pickup":"Odbiór własny"},"details":{"phone":"Telefon","email":"E-mail","company":"Firma","orderDate":"Data zamówienia","orderAmount":"Kwota","delivery":"Dostawa","deadline":"Termin","positions":"Pozycje ({n})","attachments":"Załączniki ({n})","invoice":"Pobierz fakturę","print":"Nadruk"},"chat":{"placeholder":"Wiadomość...","sendLabel":"Wyślij","attachLabel":"Dołącz plik","loading":"Ładowanie...","empty":"Brak wiadomości","fileTooLarge":"\"{name}\" przekracza 10 MB"},"files":{"empty":"Brak plików","openFile":"Otwórz plik"}},
  "contactForm":{"nameLabel":"Twoje imię i nazwisko *","namePlaceholder":"Jan Kowalski","emailLabel":"E-mail *","emailPlaceholder":"hr@firma.pl","phoneLabel":"Telefon *","phonePlaceholder":"+48 XXX XXX XXX","companyLabel":"Firma","companyPlaceholder":"Nazwa firmy","topicLabel":"Temat *","messageLabel":"Opowiedz nam o swoim projekcie","messagePlaceholder":"Ilość, rodzaj produktu, terminy...","filesLabel":"Prześlij pliki","filesClick":"Kliknij lub przeciągnij pliki tutaj","filesDesc":"Projekty, logo, obrazy...","submit":"Wyślij","submitting":"Wysyłanie...","error":"Wystąpił błąd. Spróbuj ponownie.","success":"Dziękujemy za kontakt!","successDesc":"Wkrótce się odezwiemy.","deleteFile":"Usuń {name}","topics":{"merch":{"label":"Merch korporacyjny","desc":"Koszulki, bluzy, akcesoria"},"popup":{"label":"Stoisko popup na wydarzenie","desc":"Personalizacja merchu na żywo"},"box":{"label":"Box of Touch","desc":"Fizyczne próbki przed produkcją"},"designer":{"label":"Usługi projektowe","desc":"Opracowanie lub adaptacja logo"},"bulk":{"label":"Duże zamówienie (500+)","desc":"Zamówienia hurtowe"},"other":{"label":"Inne","desc":"Każde inne pytanie"}}},
  "privacy":{"title":"Polityka prywatności","noContent":"Treść jeszcze nie dodana."},
  "terms":{"title":"Regulamin","noContent":"Treść jeszcze nie dodana."},
  "order":{"loadError":"Nie udało się załadować katalogu. Odśwież stronę."},
  "leadMagnet":{"badge":"Bezpłatnie","heading":"Otrzymaj bezpłatny mockup swojego merchu","desc":"Prześlij logo — nakładamy je i wysyłamy mockup na e-mail.","emailLabel":"Twój e-mail","cta":"Pobierz mockup","loading":"Wysyłanie...","emailError":"Podaj prawidłowy e-mail","success":"Dziękujemy!","successDesc":"Mockup dotrze w ciągu 24 godzin","formLabel":"Formularz mockupu","orCalculate":"Chcesz poznać cenę już teraz?","openCalculator":"Otwórz kalkulator cen →"},
  "popup":{"badge":"Mobilny serwis popup","heroHeading":"Popup merch na Twoim wydarzeniu —","heroSubheading":"żywe doświadczenie, które się pamięta","heroDesc":"Przyjeżdżamy do Ciebie. Goście personalizują na miejscu i odchodzą z gotowym merchem.","bookBtn":"Zarezerwuj popup","howItWorks":"Jak to działa","nav":{"useCases":"Dla kogo","how":"Jak to działa","faq":"FAQ","contacts":"Kontakt"},"book":"Zarezerwuj","footerCopyright":"U:DO CRAFT. Wszelkie prawa zastrzeżone.","menuOpen":"Otwórz menu","menuClose":"Zamknij menu","homeLink":"Strona główna","stats":{"events":"Przeprowadzonych popupów","time":"Czas personalizacji","guests":"Gości na jednym wydarzeniu","satisfaction":"Zadowolonych organizatorów"},"useCases":{"label":"Dla kogo","heading":"Odpowiedni dla każdego wydarzenia","items":{"corporate":{"title":"Eventy firmowe","desc":"Niezapomniane wydarzenie z osobistym merchem."},"conferences":{"title":"Konferencje i fora","desc":"Merch z marką na miejscu."},"festivals":{"title":"Festiwale i targi","desc":"Stoisko popup, które przyciąga uwagę."},"launches":{"title":"Premiery produktów","desc":"Premiera z merchem stworzonym przez gości."},"universities":{"title":"Uczelnie i szkoły","desc":"Uroczystości, dni otwarte, imprezy."},"b2b":{"title":"Eventy B2B","desc":"Spotkania partnerskie, targi, prezentacje."}}},"process":{"label":"Proces","heading":"Trzy kroki do idealnego popupu","steps":{"0":{"step":"01","title":"Wybierz format","desc":"Opowiedz nam o wydarzeniu."},"1":{"step":"02","title":"Przygotowujemy stoisko","desc":"Przywożymy sprzęt i odzież."},"2":{"step":"03","title":"Goście personalizują","desc":"Każdy gość odchodzi z gotowym merchem."}}},"faq":{"label":"FAQ","heading":"Często zadawane pytania","items":{"0":{"q":"Minimalna liczba uczestników?","a":"Od 50 osób."},"1":{"q":"Ile trwa personalizacja jednego produktu?","a":"Od 3 do 10 minut."},"2":{"q":"Jakie produkty są dostępne?","a":"Koszulki, bluzy, czapki, akcesoria."},"3":{"q":"Kto płaci za merch?","a":"Obie opcje są możliwe."},"4":{"q":"Ile wcześniej rezerwować?","a":"Zalecamy 2–3 tygodnie przed wydarzeniem."}}},"contact":{"label":"Zarezerwuj","heading":"Opowiedz nam o swoim wydarzeniu","desc":"Zostaw zgłoszenie — opiekun skontaktuje się w ciągu jednego dnia roboczego.","benefits":{"0":"Bezpłatna konsultacja","1":"Indywidualna wycena","2":"Odpowiedź w ciągu 24 godzin"}}}
})

print("\nAll EU locale files generated!")
print("Locales: de, fr, es, it, pl")
